targets/repository.proj

Default git behavior has changed over time and people can have different `core.eol` and `core.autocrlf` settings, which can cause issues when we try to apply patches.  This change makes us use text patching instead of binary, which handles differing line endings.

Use non-binary patching to work around different line endings than we expect.

---

netci.groovy

These will be re-enabled as we fix issues.
Leave the non-PR legs in for now as these are less visible.

Remove PR legs we currently expect to fail.

---

patches/cli/0012-allow-intermediate-package-cache.patch
patches/core-setup/0008-add-intermediate-packages.patch
patches/sdk/0002-Unify-versions.patch
patches/xliff-tasks/0001-build-pack-project.patch

This changeset introduces the fixes required to get a clean master and a passing CI. The struggle mainly comes from the fact that there are now 2.0.0 versioned packages from products in the official feeds.

Add patches to unblock CI.

---

targets/repository.proj

cc @karajas 
While trying to make this work on other OS's we have to needlessly pull in this dependency and the entire forked patch mechanism doesn't seem necessary so just always use git apply instead of patch.

Switch to always using git apply to eliminate patch dependency

---

repositories.props

For each `<Branch>` that didn't contain the submodule commit, I used `git branch --contains` and `git tag --points-at` to find reasonable values. I tried to pick the option that looked most correct when there was more than one.
Fixes https://github.com/dotnet/source-build/issues/112

Fix repo branches to match submodules

---

.gitattributes
dir.props
patches/cli-deps-satellites/0001-Allow-cli-deps-satellites-to-skip-signing-on-Windows.patch
patches/nuget-client/0004-Only-build-netstandard-and-netcoreapp-assets-on-NIX.patch
targets/cli-deps-satellites.props

/cc @crummel @dagood @weshaggard @jaredpar

Fix cli-deps-satellites on windows to not sign the satellites during source-build, since we are using a dummy RoslynTools package.

---

build.ps1

Given we are wrapping in a script block we need to capture the
args for the root script outside of the script block.
@eerhardt

Fix args passed to build.proj from build.ps1

---

dir.props
patches/cli-deps-satellites/0001-Allow-cli-deps-satellites-to-skip-signing-on-Windows.patch
patches/nuget-client/0004-Only-build-netstandard-and-netcoreapp-assets-on-NIX.patch
patches/websdk/0001-Support-building-on-nix.patch

Don't build for desktop during source-build, since the ref assemblies don't have all the desktop APIs.
Also renaming DotNetBuildFromSource parameter to match the spec.

Fix websdk on Windows

---

tools-local/init-build.proj

The dummy packages are starting to get in our way as we update to the latest shas for the submodules and as best we can tell they aren't needed at all unless you are in offline mode so I've conditioned them to only be built in offline mode.
cc @crummel @karajas @eerhardt

Only build dummy and ref packages when building in offline mode

---

patches/vstest/0009-Suppress-Mono-check-during-build.-See-https-github.c.patch
targets/vstest.props

The vstest repo is failing to build on my machine because I have mono installed on it.
Adding a patch to vstest to disable the special mono checking until https://github.com/Microsoft/vstest/issues/1153 is fixed.

Allow VsTest repo to build on machines with Mono installed

---

init-tools.msbuild
tools-local/init-build.proj

In order to override the Tools directory from source-build in
coreclr repo we need to include this extra tools package.
@eerhardt this should get us past the coreclr build issue on Windows.

CoreCLR needs another package to build

---

cross/armel/tizen-fetch.sh
netci.groovy
targets/core-setup.props
targets/coreclr.props
targets/corefx.props

Also includes a few Tizen build improvements:
- Building cross filesystem has changed.
- Synchronize build arguments for submodules with official builds.

Temporarily disable Tizen build.

---

repos/coreclr.proj

Resolves https://github.com/dotnet/source-build/issues/200
Brings in https://github.com/dotnet/coreclr/pull/14518 (and https://github.com/dotnet/coreclr/pull/14538) which implements the auto dependency flow Repo API, and configures coreclr.proj to use it.

Use CoreCLR dependency flow Repo API implementation

---

Documentation/RepoApi.md

Addresses the concerns in #194 by following the recommended approach in that issue.
This approach isn't 100% POSIX compliant, but it close enough to work correctly on UNIX systems and works for Windows as well.
/cc @dotnet/source-build-contrib

Update Repo API parameter passing.

---

repos/coreclr.proj

This makes CoreCLR try to produce packages where it would normally skip doing so, e.g. Fedora 26. This allows the CoreCLR dependency to flow.

Always pass CoreCLR msbuildonunsupportedplatform

---

netci.groovy

One of these commits fixed build legs that we turned off early on:
- https://github.com/dotnet/source-build/commit/1419ce26d185aedf52f8e05c448404eb5c3d9619
- https://github.com/dotnet/source-build/commit/11e7c09c7d2d3f58c49434088f167bfd62241769
- https://github.com/dotnet/source-build/commit/64a17297999f9a3102c6a42d621be40f23256708
- https://github.com/dotnet/source-build/commit/14d33dc2af2be062d842ff93c8410e34b6b89a93
- https://github.com/dotnet/source-build/commit/393b117dbf586562af74ca2370055808c783ef19
However, the build failed on these for other reasons so it's hard to determine exactly which one it was.  The output from these builds does appear to be correct, so this change turns the legs back on so we can track if we break them again.

Enable legs that have been fixed.

---

scripts/bootstrap/buildbootstrapcli.sh

This change adds a script that automates creating bootstrap CLI.
While there is still space for improvements in the script, I think
it is time to publish it. I have used it to bring up RHEL 6 and
Alpine and tested it on FreeBSD for x64. I have also tested
it on arm64 Linux.

Add new OS bootstrap script

---

repos/core-setup.proj
repos/coreclr.proj

This patch makes coreclr and core-setup leave debug symbols in their built native code instead of stripping it out.
After this patch, native symbols are only missing in corefx. A separate PR in corefx will take care of that: https://github.com/dotnet/corefx/pull/24979. But this fix for core-setup and coreclr is independent and doesnt need that PR to work.
The final dotnet product, after both these fixes, should contain native debug symbols for all native binaries.
I used this to verify the final built product: https://gist.github.com/omajid/766aef59857de9fc1eab173119143abc
Resolves #267

Dont strip native debug symbols during build

---

Documentation/boostrap-new-os.md

This change adds a document on creating a bootstrap cli for a new
unsupported OS.

Add new OS bootstrap doc

---

build-source-tarball.sh
build.ps1
build.sh
check-submodules.ps1
check-submodules.sh

Fixes #137.
- Make sure submodules are initialized and optionally do this for you.
- Check if submodules match their checked-in hash and optionally update them if they don't.
- Check for untracked changes in submodules and optionally clean them.
- Put which submodule versions we're using into the tarball.

Add scripts to make working with submodules easier.

---

build-source-tarball.sh
netci.groovy
src/reference-assemblies/Directory.Build.props
support/tarball/build.sh
tools-local/init-build.proj

Changes to enable building of the tarball from source-build and setting up CI for Offline build.  Offline build is building through corefx for now until other repos can get fixed.
Fixes dotnet/source-build#191

Fix build source tarball and enable CI for Red Hat Offline build

---

build.proj
repos/cli-deps-satellites.proj
repos/corefx.proj
repos/dir.targets
repos/roslyn.proj
repos/xliff-tasks.proj

Wes already fixed most of #138 with the build system overhaul; this is just a couple minor cleanups for the subrepos.
- Stop after the first error.  This also means the "See <repo>.log for details" message will now correctly identify the broken repo.
- Remove explicit filename log parameter on xliff-tasks and cli-deps-satellites.  This stops those repos from outputting to the screen as well as the file during the build with `MinimalConsoleLogOutput=true` (I am not exactly sure why this is.  If there is a more appropriate fix let me know).
- Add messages for packaging and some custom steps so we don't hang between repos with no status reporting.

Some improvements for building subrepos.

---

build-source-tarball.sh

While looking to implement https://github.com/dotnet/source-build/issues/296 I saw it was already added in https://github.com/dotnet/source-build/pull/283.
This PR makes some minor modifications to the implementation.
The net result is previously a file was created `commits.txt`
```
path	checked-in	actual
source-build	e0c33c7e8e023cf581b8816cad1b85496d49c7b3	e0c33c7e8e023cf581b8816cad1b85496d49c7b3
/home/tmds/repos/source-build/src/application-insights	9b5b49f2a7697a2bf38f09ca2f2c97326c49d93b	9b5b49f2a7697a2bf38f09ca2f2c97326c49d93b
/home/tmds/repos/source-build/src/cli	b18db615946288f2f9028dfe333d775b7f180598	b18db615946288f2f9028dfe333d775b7f180598
/home/tmds/repos/source-build/src/cli-deps-satellites	6af7f37eddcc3efb47821535a9be7bda9134f4f0	6af7f37eddcc3efb47821535a9be7bda9134f4f0 …
```

Update tarball commit info to include git describe

---

repos/dir.targets
repos/nuget-client.proj

Having "Build" as an AfterTargets on WriteVersions caused it to run right after build, which also caused GatherBuiltPackages to run early.  This resulted in GatherBuiltPackages being called before Package in Roslyn, so no output was being copied.  Removing the "Build" from AfterTargets causes all the targets to run in the right order.
Also, the nuget-client packagesOutput was incorrect, causing no output for that as well.
Fixes #308 & #309

Fix roslyn and nuget client output problems

---

repos/application-insights.proj
repos/common.proj
repos/vstest.proj

appInsights output is in a different location than where source-build was looking.  common and vstest don't implement outputPlacementRepoApi, so turn that off.
Fixes dotnet/source-build#318

Update appInsights, common and vstest to place output correctly.

---

build-source-tarball.sh

Fixes errors like
`rm: cannot remove ‘../tarball-output/src/websdk/.git’: Is a directory`
running build-source-tarball.sh.

Recursively remove .git directories.

---

patches/roslyn-tools/0001-Add-solution-for-only-.NET-Core-projects.patch
patches/roslyn-tools/0002-Update-projects-to-only-build-and-pack-for-.NET-Core.patch
repos/known-good.proj
repos/roslyn-tools.proj

- Add source-build sources to the environment variables roslyn-tools uses for extra feeds.
- Use RepoBuild instead of BuildCommand to propagate environment variables.
- Add roslyn-tools back to known-good.

Fix roslyn-tools offline build

---

repos/common.proj
repos/known-good.proj
repos/newtonsoft-json.proj
repos/websdk.proj
tools-local/init-build.proj

Updates to known-good projects to make sure that they don't use network resources.  I removed roslyn-tools and coreclr from known-good because they had some larger issues and I want to get this going in CI now.

Repair offline build

---

netci.groovy

- Change existing "Offline" builds to be called "Tarball" instead since it was inaccurate.
- Add new "Unshared" builds that work similarly to the tarball build, but build in Docker for two reasons:
- We can use `--network none` to take the machines offline.
- We can guarantee we won't have anything in the NuGet cache to pick up.

Add unshared build to Jenkins.

---

Documentation/boostrap-new-os.md

These dependencies are removed from CoreCLR for v2.1.

Mark dependencies that aren't required since 2.1

---

dir.props
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj

This should cause any `p:PortableBuild=_X_` properties passed to the top level `build.sh` to also set the appropriate flags in the appropriate sub-projects, while leaving their defaults in place.
The default is still to produce non-portable builds.
This also fixes corefx to build both times with non-portable builds.
This is a manual port of https://github.com/dotnet/source-build/pull/302 to `dev/release/2.1` branch. I am going to need it for https://github.com/dotnet/source-build/issues/380
cc @aslicerh @dleeapho @weshaggard

Pass PortableBuild setting from top level build script to sub projects

---

build-source-tarball.sh
build.proj
dependencies.props
dependencies.targets
dir.props
init-tools.msbuild
repos/application-insights.proj
repos/cli-migrate.proj
repos/clicommandlineparser.proj
repos/common.proj
repos/dir.props
repos/dir.targets
repos/javascriptservices.proj
repos/known-good.proj
repos/msbuild.proj
repos/netcorecli-fsc.proj
repos/newtonsoft-json.proj
repos/nuget-client.proj
repos/roslyn-tools.proj
repos/sdk.proj
repos/standard.proj
repos/symreader-portable.proj
repos/symreader.proj
repos/vstest.proj
repos/xliff-tasks.proj

To try it out, use `build.cmd /t:UpdateDependencies` to update based on the `ProdConCurrentRef` source of truth (e.g. if you want to pin to a specific ProdCon build) and `build.cmd /t:UpdateToRemoteDependencies` to update to the latest manifest on dotnet/versions master.
Uses new updater and dependency info from https://github.com/dotnet/buildtools/pull/1968.
There's some metadata checked into the project files that this updater won't change. I have a followup issue for that: https://github.com/dotnet/source-build/issues/370.
https://github.com/dotnet/source-build/issues/342
Also adds a BuildTools updater: https://github.com/dotnet/source-build/issues/270

Auto-update submodules to the commits used in latest ProdCon build

---

repos/cli.proj

This environment variable is obviously not necessary since it doesn't use the right name, meaning it isn't doing anything currently.
We can add this back later, if we need it.

Remove unused Item

---

netci.groovy

This will hopefully let us get repro machines easier for this leg.
The *offline* tarball works fine as-is, since it actually uses Ubuntu with RHEL Docker containers. But it's possible for something to fail in the online leg that doesn't fail offline.

Add CentOS7.1 online tarball CI leg

---

repos/dir.targets
repos/fsharp.proj
repos/known-good.proj

VisualFSharp changes are based on https://github.com/Microsoft/visualfsharp/pull/4674, which adds the `DotNetPackageVersionPropsPath` repo API.

Add fsharp to known-good

---

dir.props
repos/coreclr.proj

See https://github.com/dotnet/source-build/issues/380. For some examples of why we would want to use the system libraries, see:
- https://fedoraproject.org/wiki/Bundled_Libraries
- https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code
- https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
`UseSystemLibraries` lets users control if they want to use the system versions of libraries or bundled libraries. The only use case where this applies currently is coreclr's libunwind.
This PR by itself wont do anything until we pull in a version of coreclr that includes the implementation of `CLR_CMAKE_USE_SYSTEM_LIBUNWIND`. Currently the option is not understood and just ignored by coreclr's build system.

Introduce a UseSystemLibraries option to use the system libunwind

---

repos/fsharp.proj

This will keep the build order intact once we switch the root project from known-good to cli.

Uncomment fsharp's core-setup RepositoryReference

---

repos/dir.targets

Minor dev scenario fix.
`git apply` by itself takes input from stdin, which makes the build seem to hang. If the patches dir exists but no patches are inside it, skip the command. (This can happen if you delete all patches but don't delete the directory on a local build.)
FYI @weshaggard

Avoid running "git apply" with no arguments

---

repos/msbuild.proj

msbuild repo turned off nerdbank versioning for source-build.  So, we need to override versioning parameters to ensure the built version is correct.

Set version information for msbuild project

---

patches/cli/0002-Make-BuildFromSource-disable-ASP.NET-dev-certs.patch

Before this change, the certificate generation would no-op but the CLI would tell the user it generated a cert. This adds the `DOTNET_BUILD_FROM_SOURCE` conditional to the right place to prevent that.
---
Fixes https://github.com/dotnet/source-build/issues/434

Fix cli/aspnet dev cert gen patch: fix message

---

netci.groovy

Putting this in a separate PR so we don't have to work with the jobs generated by https://github.com/dotnet/source-build/pull/445 while I work on fixing other things about #445.
If this looks ok, I'll merge before CI passes. (Already validated by running a bunch of successful jobs on the generated CI, IMO.)

Make all tarball build timeouts 4 hours

---

netci.groovy
patches/cli/0010-Roslyn-plat-assembly-paths-for-RemainingTargets.patch
patches/roslyn/0002-Add-VBCSCompiler-to-SourceBuild.sln.patch
repos/cli.proj
repos/roslyn.proj

Start building the Microsoft.NETCore.Compilers package so that CLI can uptake it and crossgen it.
This is https://github.com/dotnet/source-build/pull/444 plus enabling CLI's crossgen step.
Fixes https://github.com/dotnet/source-build/issues/427

Enable CLI crossgen, add Microsoft.NETCore.Compilers

---

patches/cli/0010-Set-AspNetCore-version-to-final.patch

Update the version of AspNetCoreApp in CLI to point to the final build, since source-build doesn't build this and it doesn't get placed in the PackageVersionsProps file.

Set AspNetCoreApp version to final

---

build-source-tarball.sh

* Instead of cleaning/resetting submodules, use "git checkout" to add clean submodule sources to the tarball.
* Add a few status log echos.
The main reason to do this is to diagnose issues with a built tarball. There's a **lot** of useful information in the submodules.
This also makes it possible to do a partial rebuild of the repo, then make a new tarball, rather than having to build from scratch every time. This is still dangerous due to potential dirty repo, packages dir, and bin state, but better (IMO) than doing live edits to a tarball and mirroring them in the repo.
`git submodule foreach` runs in the context of a new shell, so I had to `export` the variables it uses.

Avoid cleaning submodules in build-source-tarball

---

build-source-tarball.sh
build.proj
dir.props
repos/cli-migrate.proj
repos/cli.proj
repos/clicommandlineparser.proj
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
repos/dir.props
repos/dir.targets
repos/msbuild.proj
repos/roslyn-tools.proj
repos/roslyn.proj
repos/sdk.proj
repos/standard.proj
repos/symreader-portable.proj
repos/symreader.proj
repos/templating.proj
repos/xliff-tasks.proj
tools-local/init-build.proj

Fixes https://github.com/dotnet/source-build/issues/385.
The generated files go into `bin/git-info/{repo}.props`, and that `git-info` dir gets copied into the tarball at the root. The props files are used in the main build and tarball build to keep them as similar as possible, rather than only generating them for the tarball build.

Remove checked-in Git info: get during build

---

tools-2.0.0/init-tools.sh

This should allow the script to be executed rather than only sourced.
Fixes the problem where the 2.0.0 init-tools is always restored because the `return` no-ops mentioned here: https://github.com/dotnet/source-build/pull/462#pullrequestreview-114135548.
Check out https://github.com/dotnet/source-build/pull/464/files?w=1 for a better view.

[release/2.1.0-preview2] Fix early returns: wrap init-tools in a function

---

patches/nuget-client/0001-Add-XPlat-build-properties-to-NuGet.Credentials.patch
repos/cli.proj
repos/known-good.proj

Adds a patch to make NuGet.Credentials XPlat as it is now referenced from NuGet.Commands.  Patch removal submitted to https://github.com/NuGet/NuGet.Client/pull/2184.

Fix nuget-client build for RC.

---

patches/templating/0001-Add-source-build-exlusion-to-resetting-output-paths.patch
repos/known-good.proj

Don't use the `scratch` directory as we aren't signing the templating packages.  Looking at this closer now to see what a good upstream fix looks like, trying this out to make sure it gets through the whole build.

Add patch to not reset output paths for templating.

---

build-source-tarball.sh
build.proj
dir.props
repos/dir.targets
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/ReadNuGetPackageInfos.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/WritePackageUsageReportToFile.cs

These reports look in the source tree for `project.assets.json` files that contain any of the prebuilt packages. The report runs in two parts of the build:
* When running `build-source-tarball.sh`. This helps figure out why a prebuilt package was downloaded, and target efforts to remove them.
* To disable this report, `export SOURCE_BUILD_SKIP_PREBUILT_REPORT=1`
* After building the tarball (offline), see what was restored from the prebuilt dir in practice. This will likely be smaller than the online build. The diff between the online and offline report might show us some packages that are easy to get rid of.
* To disable this report, pass `/p:SkipReportPrebuiltUsageAfterOfflineBuild=true`
(The reports take a minute, so I included skips in case they slow down a dev loop at some point.) …

Generate prebuilt package usage reports

---

repos/corefx.proj

@dseefeld this should fix the issue you are seeing with corefx not publishing packages.
Looks like when we tried to fix the corefx/coreclr package builds we based it off the wrong property.
https://github.com/dotnet/corefx/pull/28607
https://github.com/dotnet/coreclr/pull/17323
In those PR's we based it on DotNetBuildOffline but that is only set in the tarball not the source-build. We should instead update corefx and coreclr to use DotNetBuildFromSource for these conditions. I will submit a PR to change them. 
Note that I'm only workaround the corefx in this PR because we don't actually use the identity packages from coreclr in our other builds.

Force corefx to build identity and runtime packages

---

patches/cli/0011-Set-AspNetCore-version-to-final.patch

Update `2.1.0-preview2-final` to `2.1.0-rc1-final`.
I'm not sure how well this will work with `Microsoft.AspNetCore.All` `2.1.0-rc1-final` not being released yet.

Update AspNetCore package version used by CLI to 2.1.0-rc1-final

---

smoke-test.sh
smoke-testNuGet.Config

Updated the smoke-test to provide options for testing both local restore sources and online restore sources.
Also, added a --minimal option to run just the non-web tests with local restore source.

Update smoke test to allow local restore source testing

---

repos/msbuild.proj

msbuild was updated to use a newer version of repotoolset.  It now expects VersionPrefix instead of VersionBase.

Update msbuild version info to use property expected by repotoolset

---

build.proj
dir.props
repos/dir.targets
tools-local/earlier-prebuilts.targets
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/Usage.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/UsageAnnotation.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/UsageData.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/UsageGrouping.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/WritePackageUsageData.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/WriteUsageReports.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/WriteBuildOutputProps.cs

Include additional information when available. Split report process into two stages: allow regenerating the report on a different machine with additional information.
I've been using this to generate reports with the extra info by copying `bin/prebuilt-report` to my local (Windows) repo `bin/prebuilt-report`, adding in a `build.xml` from dotnet/versions and `poisoned.txt` from @crummel, and running `.\build.cmd /t:CreatePrebuiltUsageReport`.

Improve prebuilt package report

---

build-source-tarball.sh
smoke-test.sh

Update sed command, since OSX expects an extension on the -i command.
Remove usage of readlink, since path is already absolute.

Fix smoke test for OSX

---

repos/clicommandlineparser.proj

Fix CliCommandLineParser build manifest name.

---

repos/cli-migrate.proj

New ProdCon builds include the source-build fix commits.

Add cli-migrate to auto-update

---

repos/dir.props

This will make produced versions only use "-rc1" suffixes instead of "-rc1-buildnumber", which matches up with the official RC1 release.

Add VersionStamp to CoreFX and core-setup builds.

---

netci.groovy

Mac jobs have been timing out very close to the end of the build, up the timeout from two hours to three hours.

Extend timeouts for push and PR jobs.

---

ProdConFeed.txt

Updates ProdCon feed to latest from `2.1-rtm`. This would only affect the result if the prebuilt SDK packages changed between these builds, which seems unlikely.

Update ProdCon feed to 20180515-07

---

netci.groovy
smoke-test.sh

This gets the aspnetcore smoke-tests working, both with and without dev certs. I changed the 20 second delay to check every second up to 20 to see if the project's ready--this speeds it up a bit.
The challenge was figuring out why SIGINT wasn't working as expected. It turns out to be new behavior in 2.1 because https://github.com/dotnet/coreclr/pull/15393 makes .NET Core preserve `SIG_IGN` (signal ignore) when it's set on SIGINT. ~~I added `set -m` to avoid `SIG_IGN` being set when our `dotnet run` is backgrounded. (https://unix.stackexchange.com/a/356480)~~ I changed it to SIGTERM per @tmds's suggestion.

Add web to smoke-test, with and without dev certs

---

Documentation/README.md
Documentation/boostrap-new-os.md
Documentation/tool-dependencies.md

- Add steps to the README how to build from the tarball
- Add bootstrap steps on how to build with the bootstrap SDK
- Add a list of tools required to build .NET Core

Add more source-build documentation

---

patches/msbuild/0001-Add-TargetingPack-and-enable-net46-builds-for-source.patch
patches/nuget-client/0001-Add-TargetingPack-and-enable-net46-builds-for-source.patch
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
repos/nuget-client.proj
repos/sdk.proj

Testing build with net46 changes

Upgrade to latest prodcon build and add targeting packs for net46 support

---

tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/GetHostInformation.cs

fixes following error when executed on FreeBSD
/usr/home/furt/git/source-build2/tools-local/init-build.proj(70,5): error : Could not determine display name for platform.

add  FreeBSD

---

repos/clicommandlineparser.proj
repos/dir.props
repos/msbuild.proj
repos/roslyn-tools.proj

A while ago when doing the initial investigation on what was needed to build the whole stack on Windows I fix some of the submodules.
Contributes to: https://github.com/dotnet/source-build/issues/575
cc: @dagood @weshaggard

Windows fixes in order to be able to build some submodules from master

---

dir.props
repos/cli.proj
smoke-test.sh

* Update RootRepo to build through cli for everything but Windows
* Remove build args and flags that no longer apply to cli
* Update RepositoryReferences to only include ones used by cli

Update cli project to build cli after repo refactoring

---

.vsts-ci.yml
.vsts.pipelines/builds/vsts_prodcon_update.yml
.vsts.pipelines/steps/docker-cleanup-linux.yml
build-source-tarball.sh
build.proj
dependencies.props
dependencies.targets
dir.targets
fetch-vsts-commits.ps1
fetch-vsts-commits.sh
repos/cli.proj
repos/dir.props
repos/dir.targets
repos/nuget-client.proj
smoke-test.sh
smoke-testNuGet.Config

The 2.1.2 release saw some changes in `release/2.1` infra to support VSTS builds. This merge takes those changes into `master` for the future. I made some edits to the merge commit to fix conflicts and remove any submodule upgrades related to the 2.1.2 release.
**Don't squash this PR.** Squashing https://github.com/dotnet/source-build/pull/577 (an earlier 2.1 => master merge) made some commits it included to show up in this PR's commit list, too.

Merge release/2.1 infrastructure changes into master

---

extract-patches.sh

Small improvement to `extract-patches.sh` to simplify patch workflow:
1. `git am ../../patches/<repo>/*`
2. Make changes, fixups, etc.
3. `../../extract-patches.sh`
4. Reset inadvertent changes to existing patch files due to client formatting or the new "From" commit hash.

Detect the base commit in extract-patches.sh

---

.gitmodules
dir.props
patches/cli/0001-Fix-OrchestratedPackageVersionProps-for-source-build.patch
patches/cli/0002-Fix-archiving-to-.zip.patch
patches/cli/0003-Use-netcoreapp3.0-for-compatibility-with-everything-.patch
patches/core-sdk/0001-Add-dependency-for-restoring-packages-before-trying-.patch
patches/core-sdk/0002-Experimental-change-to-fix-OSX-don-t-think-we-need-t.patch
patches/nuget-client/0001-Add-TargetingPack-and-enable-net46-builds-for-source.patch
patches/toolset/0001-Update-CLI-version-update-BranchName-and-Channel.patch
patches/toolset/0002-Change-choice-of-tarball-zip-to-be-based-on-extensio.patch
patches/toolset/0003-Remove-LKG-SDK-download-for-source-build.patch
patches/toolset/0004-Use-netcoreapp3.0-target-frameworks-to-match-the-res.patch
patches/toolset/0005-Update-CLI-internal-version-to-match-what-source-bui.patch
repos/cli.proj
repos/core-sdk.proj
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
repos/fsharp.proj
repos/known-good.proj
repos/msbuild.proj
repos/nuget-client.proj
repos/toolset.proj
smoke-test.sh
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/PublishCoreSetupBinaries.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/PublishToolsetBinaries.cs

Most of the work here was in adding the new toolset and core-sdk repos and adjusting our current process to the way they work.  I also had the usual build number/hash updates.  This includes a few workarounds and patches that I believe are all tagged with an associated issue or PR:
- `PublishToolsetBinaries` is a near-duplicate of `PublishCoreSetupBinaries` with a changed regex: https://github.com/dotnet/source-build/issues/554.
- `smoke-test.sh` always skips some tests and replaces the TFM in projects: https://github.com/dotnet/source-build/issues/635.
- Several patches among core-sdk, toolset, and CLI.  These have the issues in their descriptions.

Update source-build master to core repo masters

---

Documentation/boostrap-new-os.md
scripts/bootstrap/buildbootstrapcli.sh

Bootstrapping works with a seed CLI. The CLI distributed by Microsoft is a release build. The CLI built by source-build is a release build. There's a much greater chance that the default cli will be a release build rather than a debug build. An incompatible configuration will not work. So change the default from debug to release to make it more likely to work.
Also update the docs to point out that the seed CLI configuration must match the configuration being used here or the dotnet command will fail at runtime with cryptic error messages.

Change default bootstrap type to release

---

build-source-tarball.sh
smoke-test.sh

Add an arg parsing loop, and stop running if something isn't recognized. For example, this prevents destroying my dev build if I spell "--skip-build" wrong or get the arg order incorrect.

Catch some bad build-source-tarball args and exit

---

build-source-tarball.sh
smoke-test.sh

Port https://github.com/dotnet/source-build/pull/674 to release/2.1 (clean cherry-pick)
Once this goes in, we should get a automatic merge PR to release/2.2 via https://github.com/dotnet/versions/pull/339.
> * Catch some bad build-source-tarball args and exit
> 
> Add an arg parsing loop, and stop running if something isn't recognized. For example, this prevents destroying my dev build if I spell "--skip-build" wrong or get the arg order incorrect.
> 
> * Use exit code 0 for "--help"
> 
> Also add unrecognized arg print in smoke-test.sh.
> 
> * TARBALL_ROOT already existing isn't an error
> 
> CI creates TARBALL_ROOT before building the tarball. Still include the message as informational in case it's useful to diagnose other scenarios.
> 
> (cherry picked from commit …

[release/2.1] Tarball build, smoke-test startup fixes

---

netci.groovy

I noticed some missing logs while doing the master branch work - not all repos are using binlogs yet so we're missing out on some logs.  This also adds more logs that source-build itself produces.

Add more logs in the archive settings.

---

scripts/bootstrap/buildbootstrapcli.sh

`scripts/bootstrap/buildbootstrapcli.sh` claims to work with this invocation:
./scripts/bootstrap/buildbootstrapcli.sh -rid linux-x64 -seedcli Tools/dotnetcli/
But it fails with an error:
realpath: linux-x64/dotnetcli: No such file or directory
Adding a `set -x` shows:
+ __build_arch=x64
+ [[ -z '' ]]
++ getrealpath linux-x64/dotnetcli
++ command -v realpath
++ realpath linux-x64/dotnetcli
realpath: linux-x64/dotnetcli: No such file or directory
+ __outputpath=
This error is caused by the use of `realpath` (or `readlink -e`) on the computed value of `$__outputpath` before the directory has been created.
The directory is actually created later on by this script, so the fix is to just defer the `realpath` invocation until the script has done an `mkdir -p` on it.

Fix buildbootstrapcli.sh for non-existing outputpath dir

---

scripts/bootstrap/buildbootstrapcli.sh

This makes it easier to bootstrap incompatible Linux x86_64 distributions. The existing builds of .NET Core won't run there but the boostrap script will still (indirectly) try and run `dotnet` when building coreclr. That `dotnet` invocation will fail causing the bootstrap process to fail.
This depends on the coreclr ~~submodule~~ of the version being bootstrapped to include https://github.com/dotnet/coreclr/pull/19111 to correctly fix the issue. Otherwise there wont be any difference and `dotnet` might still be executed.
Fixes #663

Do not run dotnet when bootstrapping coreclr

---

README.md
arm-ci.sh
armdeps.sh
build-source-tarball.sh
build.sh
check-submodules.sh
docker/build-docker-images.sh
extract-patches.sh
scripts/docker/docker-run.sh
smoke-test.sh
support/tarball/build.sh

* The build notes about Windows and macOS at [./README.md](https://github.com/dotnet/source-build/tree/e45f8c0/README.md) were contradicting with [Documentation/README.md](https://github.com/dotnet/source-build/tree/e45f8c0/Documentation/README.md); now they are aligned.
* Bash is not situated at `/bin/` on every Unix-y OS; use `/usr/bin/env` to find `bash` path.

Update build docs and fix bash shebangs

---

netci.groovy

Some issue only repro with an only tarball build - e.g. PR #653.
This is a partial reversion of b5a02e93099cbef7ad5e6fce3800903322859f7c - I left the offline CentOS build leg in.

[release/2.1] Add online tarball builds back in.

---

.vsts.pipelines/phases/ci-linux.yml

* Create two tarballs: split the smoke test prereqs into a separate tarball. They aren't required at all for builds, and for smoke-test, they're only required when the packages can't easily be acquired through the usual endpoint.
* Reduce `prebuilt/smoke-test-packages/` from an expanded NuGet package cache to a directory of nupkg files. This eliminates the redundancy of having both the nupkgs and their expanded contents in the tarball. (290 MB => 146 MB.)
* Set the working directory so the tarball has the `tarball_<build number>` dir in it, not `tb/tarball_<build number>` (absolute path).
We did these fixes by hand a few times--it'll be nice to get them in by default.
The tarball's still missing a nice name. Right now it's like `tarball_1967206-smoke-test-prereqs.tar.gz`. I can't think of …

[release/2.1] Split smoke test prebuilts out of main tarball

---

build-source-tarball.sh
dependencies.props
dependencies.targets
netci.groovy
repos/cli.proj

I think we should try to turn on automation to merge `release/2.2` => `master`. This would let us make infra PRs once to `release/2.1` and they'd be merged automatically to `release/2.2` then `master`. I made this one-time cleanup merge (wasn't too bad) to prepare. Think this makes sense?

 Merge branch 'release/2.2' into 'master'

---

repos/application-insights.proj
repos/core-setup.proj
repos/corefx.proj
repos/javascriptservices.proj
repos/netcorecli-fsc.proj
repos/nuget-client.proj
repos/roslyn.proj
repos/templating.proj
repos/websdk.proj
repos/xliff-tasks.proj

In trying to troubleshoot a couple build issues I realized that MSBuild binlogs were nice to have.  This change adds binlogging everywhere we can without changing the submodules' build scripts.  It also fixes up submodules' `RepoBuild`s so that they execute with the project directory as their current directory - this was the cause of getting random log files in the `repos` directory.

Add more binlogging

---

build.proj
dir.props
netci.groovy
repos/dir.props
repos/dir.targets
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/WritePackageUsageData.cs

A few improvements to prebuilt baselining: #770, #774.

Improve prebuilt baselining: warn on error by default, save all project.assets.json

---

netci.groovy

[release/2.1] Add portable builds to CI.

---

.gitmodules
dependencies.props
init-tools.msbuild
patches/linker/0001-Add-an-option-to-use-reflection-heuristics-during-ma.patch
repos/coreclr.proj
repos/corefx.proj
repos/linker.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Add a simple project for linker, and use the built tool in CoreCLR and CoreFX.
Uses a patch to add "-h" arg and reflection heuristics feature.
Update baselines: removes ILLink.Tasks, adds additional versions of some existing packages.
Patch removal tracked by https://github.com/dotnet/source-build/issues/777.
https://github.com/dotnet/source-build/issues/580

Add mono/linker submodule for source-built ILLink.Tasks

---

repos/dir.targets
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/AnnotatedUsage.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/WriteUsageReports.cs

Use some extremely simple checks against the project.assets.json path to determine which usages are performed by a test project, and which package-versions are restored only by test projects. These are added to `annotated-usage.xml` as `TestProjectByHeuristic="true"` (per usage) and `TestProjectOnlyByHeuristic="true"` (added to all usages of the package-version).
Also, write usage reports before baseline validation to make sure info is always generated.
https://github.com/dotnet/source-build/issues/730

Find test-only prebuilts with simple path patterns

---

repos/application-insights.proj
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
repos/msbuild.proj
repos/nuget-client.proj
repos/roslyn.proj
repos/sdk.proj
repos/templating.proj
repos/vstest.proj
repos/websdk.proj
repos/xliff-tasks.proj

I like splitting args across lines because:
* Diffs (especially 3-way for merging) are hard to read with long lines.
* Automatic diffing can be smarter when the parts are grouped like this.
* Actual conflicts are more likely to be resolvable using basic choose A/B/C.
In a few cases I was able to share some parameters that were duplicated before.

Organize build args for readability/mergeability

---

patches/cli/0001-Persist-ASP.NET-runtime-patch-targeting-default.patch

Previously we were ending up accidentally setting this to a constant.  Also add a bit more detail to the comment about why this is needed.

Small fix to evaluate ASP.NET targeting patch dynamically.

---

build-source-tarball.sh
build.proj
dir.props
support/tarball/build.sh
tools-local/init-build.proj
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/CatalogFileEntry.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/CatalogPackageEntry.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/CheckForPoison.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/MarkAndCatalogPackages.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection.csproj
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/NuGet.Config
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/PoisonMatch.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/PoisonType.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/PoisonedFileEntry.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/Utility.cs

Still having some build errors locally, so I want to see what this does on all legs.

Add tasks for poisoning and checking for poison in packages.

---

build-source-tarball.sh
build.proj
dir.props
patches/linker/0002-Update-linker-to-use-2.0.0-runtime.patch
patches/newtonsoft-json/0001-Run-dotnet-migrate-to-generate-Newtonsoft.Json.Dotne.patch
patches/newtonsoft-json/0004-Add-roslyn-tools-to-nuget.config.patch
repos/cli.proj
repos/dir.targets
support/tarball/build.sh
tools-local/init-build.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/CopyReferenceOnlyPackages.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/WritePackageUsageData.cs

Adds detection of packages in the source-build build that either a) have no binaries or b) only have dlls that are in the /ref/ folder.  For ones with dlls, disassembles them with ildasm and provides the IL as source to the tarball.  When building the tarball, these assemblies are re-build with ilasm and the packages are re-packed to be available for the tarball build.
There are a couple more items to complete before this is done:
@dagood & @crummel  PTAL

Add capture and re-build of reference-only packages to eliminate prebuilts

---

.vsts.pipelines/builds/ci.yml
.vsts.pipelines/phases/ci-linux.yml
.vsts.pipelines/phases/ci-osx.yml
.vsts.pipelines/steps/calculate-config-flags-linux.yml
.vsts.pipelines/steps/docker-cleanup-linux.yml
.vsts.pipelines/steps/init-submodules-sh.yml
build.proj
patches/coreclr/0001-Don-t-check-for-libintl.h-on-Darwin-OSX.patch
repos/websdk.proj

CentOS, Ubuntu 16.04, and OSX legs included.
Fedora 28 and Debian 8.2 builds don't work yet due to the images we're using missing tools/libs, filing issues to track those. (https://github.com/dotnet/source-build/issues/814, https://github.com/dotnet/source-build/issues/815.)
I haven't tried these new defs with internal changes yet (`user.PAT`). I tried to keep the functionality around so hopefully that will just be a quick check.
https://github.com/dotnet/source-build/issues/757

Add Azure DevOps dnceng instance CI YAML

---

dependencies.props
repos/cli.proj
repos/dir.props

Port infra parts of https://github.com/dotnet/source-build/pull/821 that centralize version stabilization/prerelease props and apply them better. This also puts them in the dependencies.props file as they should be to implement https://github.com/dotnet/source-build/issues/550.

Port 2.2.0-preview3 version infrastructure to 2.1

---

README.md
scripts/generate-readme-table.sh

Clean view: https://github.com/dagood/source-build/blob/azdo-badges/README.md
Add the Azure DevOps badges in a new column. Note that the badges are externally visible but the builds the badges link to unfortunately aren't. The build is internal to allow us to work around [a feature gap between Jenkins and AzDO](https://dnceng.visualstudio.com/internal/_workitems/edit/92) by publishing a file to an authenticated endpoint during the build. (Workaround not yet implemented.)
Add a `sh` script to generate the table.

 Include Azure DevOps badges; generate README table

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-osx.yml

MSBuild says it's saving diagnostic info here when `Child node "2" exited prematurely` errors happen in CI. Save the directory to allow devs to hunt down flakiness.
We have this set up in Jenkins and haven't seen anything in this dir yet, but worth adding to our AzDO definitions too. Recently an "exited prematurely" error happened during CoreFX managed build in a CentOS leg here: https://dnceng.visualstudio.com/public/_build/results?buildId=34807&view=logs.

Publish bin/msbuild-debug dir in CI

---

.gitmodules
patches/aspnet-razor/0001-Remove-Internal.AspNetCore.Sdk-avoid-prebuilt.patch
repos/aspnet-razor.proj
repos/cli.proj
repos/known-good.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Add https://github.com/aspnet/Razor to source-build to produce `Microsoft.NET.Sdk.Razor 2.1.2`.
For 2.2, after the auto-merge, I'll apply https://github.com/dotnet/source-build/compare/be27588b9c51c8c9bef9ef60f329eef41cf868f1...dagood:add-razor-sdk-2.2 to get the DLLs building. I decompiled the source-built DLLs and they're identical to the ones on the gallery. Doing a local build of those changes and this 2.1 PR to validate prebuilt baselines.
Once the aspnet repos are merged into aspnet/AspNetCore (not as submodules) these are the steps I'm thinking we'll need to do:
* Remove `src/aspnet-razor`, add `src/aspnetcore`.
* Rename project file to match.
* Update base path.
* Add handling of the global.json (present in AspNetCore but not Razor).
* Update patches for new paths.
* (We actually …

[release/2.1] Add aspnet/Razor submodule for Microsoft.NET.Sdk.Razor

---

.gitmodules
patches/aspnet-razor/0001-Remove-Internal.AspNetCore.Sdk-avoid-prebuilt.patch
patches/aspnet-razor/0002-Add-reference-assemblies-to-allow-net46-build.patch
repos/aspnet-razor.proj
repos/cli.proj
repos/known-good.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Brings https://github.com/dotnet/source-build/pull/834 into `release/2.2` and updates the aspnet-razor submodule to `2.2.0-preview3`. A patch adds in reference assemblies so the build task DLLs (not in 2.1) can build for net46.
Finishes off https://github.com/dotnet/source-build/issues/822.

[release/2.2] Add aspnet/Razor submodule for Microsoft.NET.Sdk.Razor

---

patches/common/0001-Use-roslyn-tools-technique-to-skip-test-restore.patch
patches/corefx/0001-Skip-CoreFx.Private.TestUtilities-in-source-build.patch
patches/sdk/0001-Exclude-unit-test-projects-from-source-build.patch
patches/websdk/0001-Use-roslyn-tools-technique-to-skip-test-restore.patch
repos/templating.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

* Patch CoreFX to exclude test-related project depending on XUnit.Runtime dependency project.
* https://github.com/dotnet/corefx/pull/33217
* Patch Common and WebSDK to use the roslyn-tools "empty target override" approach to avoid test project restore.
* https://github.com/aspnet/Extensions/pull/445 (Common)
* https://github.com/aspnet/websdk/pull/421
* Patch SDK to add `ExcludeFromSourceBuild=true` to test projects.
* https://github.com/dotnet/sdk/pull/2642
* Add Templating build arg that overrides `SharedTestProjects` to empty to avoid restoring the shared test project's dependencies.
* Not a patch, no action needed by repo.
* Update prebuilt baselines.
In a full build I did, there are no `TestProjectOnlyByHeuristic` elements left in the tarball's `annotated-usage.xml` with these …

[release/2.1] Remove test-only prebuilts

---

repos/aspnet-razor.proj
repos/known-good.proj

When I added this repo to source-build, I didn't consider its dependencies. It turns out the text-only `Microsoft.NET.Sdk.Razor` package build has a dependency on `NETStandard.Library` `2.0.3`, which we source-build. In the production build, building it out of order pollutes the package cache with an online version.
This should fix the warning from https://github.com/dotnet/source-build/issues/857. (Local build hasn't completed yet to validate though.)

Add aspnet-razor dotnet/standard dependency

---

patches/templating/0001-Skip-test-related-projects-if-PB_SkipTests-set.patch
repos/dir.targets
repos/templating.proj
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/ValidateUsageAgainstBaseline.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/WritePackageUsageData.cs

After these changes, a production+offline build that I did had no test heuristic attributes in `annotated-usage.xml` at all. I added a bit to baseline validation that will fail CI if any of these get back in. (And I guess it will make sure in this CI run that I did it right. 😄)
https://github.com/dotnet/source-build/issues/846

Remove prebuilt usages classified as tests

---

.vsts.pipelines/jobs/ci-osx.yml

Fixes https://github.com/dotnet/source-build/issues/835
Parsing `brew info openssl` might be overkill (or even a bad idea?) but I'm hoping it will make us somewhat resilient to changes in how the hosted pool is set up.

Use Hosted macOS pool, set up our own prereqs

---

smoke-test.sh

In `master`, we have a workaround to replace `netcoreapp2.2` with `netcoreapp3.0`, and this happens between `dotnet new` and `dotnet restore`. `dotnet new` normally restores as part of project setup, before we have a chance to edit it, and that fails.
Jenkins ignores the error messages because we "hide" them in a log file, but the params AzDO uses doesn't and the `Exec` detects them. In theory we could change the parameters, but fixing the underlying problem means we're more likely to catch problems with smoke-test.
Copy the `# XXX temporary workaround XXX` surrounding comments from the other parts of the workaround.

Fix AzDO master CI: Pass "--no-restore" to smoke-test "dotnet new"

---

repos/application-insights.proj
repos/dir.targets
repos/netcorecli-fsc.proj
repos/newtonsoft-json.proj
repos/nuget-client.proj
repos/roslyn.proj
repos/templating.proj

> For every Exec that takes RedirectRepoOutputToLog, ignore standard error/warning format. If it isn't ignored, there might be problems that are ignored by redirecting to the logs that aren't ignored if redirecting is turned off. Configure Exec not to detect these at all to behave the same whether redirecting or not.
Should fix the type of problem seen in https://github.com/dotnet/source-build/issues/854 with `/p:MinimalConsoleLogOutput=false`. I was able to repro on `release/2.2`, merge this PR into 2.2, (clean,) then run successfully.

Set IgnoreStandardErrorWarningFormat on Execs

---

tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/AnnotatedUsage.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/Usage.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/WritePackageUsageData.cs

Add new properties IsDirectDependency and IsAutoReferenced from project.assets.json. 
IsDirectDependency means that the dependency shows up in the $.project.frameworks.<version>.dependencies section of the document.  IsAutoReferenced comes directly from the dependency.

Add IsDirectDependency and IsAutoReferenced to usage report.

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/steps/publish-prebuilt-data-sh.yml
build.proj

Publishes the prebuilt report data for tarball builds to a blob storage location. Just needs the `publish.blobStorage.*` variables specified in the internal build def.
https://github.com/dotnet/source-build/issues/851

Add PublishPrebuiltReportData target to make rolling build prebuilt data available

---

build.sh
repos/dir.targets
support/tarball/build.sh
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/GetSourceBuiltNupkgCacheConflicts.cs

> Try to find where the conflicting package came from and include the path in the message.
> 
> For example, this identifies that Microsoft.NETCore.Targets in the tarball build is being used from prebuilt/source-built. Before this change, it would incorrectly suggest the package was restored from the internet.
> 
> Add source-build infrastructure MSBuild binlogging for better diagnosis.
https://github.com/dotnet/source-build/issues/792

Improve source-built cache conflict warning

---

.vsts.pipelines/builds/ci.yml
.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-osx.yml

These were generated by Jenkins, but not by the AzDO builds so far. This adds them in on CentOS legs, similar to Jenkins. They will be picked up automatically by the rolling build publish infra because the poison report is a `xml` file alongside the other reports.
Also fixes the OSX artifact name, ~and removes the non-tarball smoke-test from tarball builds (because it's redundant vs. the Production legs' smoke-tests and delays the build by a bit)~.
https://github.com/dotnet/source-build/issues/851

Generate poison report (prebuilt leaks) on CentOS

---

repos/application-insights.proj

App-insights places its output under a path one directory up from its source based on finding an EnlistmentRoot.marker file.  This puts this output right under the source-build/src directory.  Override the EnlistmentRoot property to place it under the source-build/src/application-insights directory.  
Also need to override the RelativeOutputPathBase property because it is calculated from the EnlistmentRoot property.  This is used to differentiate between outputs in app-insight's mapping scheme, but is not needed for source-build.

Change where application-insights writes its output

---

.vsts.pipelines/jobs/ci-local.yml
.vsts.pipelines/steps/setup-windows-python.yml

Currently, the CoreCLR build silently fails in 2.1 because it can't find Python. This was caught in the auto-merge to 2.2 where the CoreCLR build fails correctly/loudly. Fix this by installing `python` to a build-local location, similar to creating a `bash` to use.

Install Python in Windows CI

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/ci-local.yml

AzDO doesn't seem to clean the submodules, so we have to until we can switch off the pool with persistent agents.
Saw this happen in https://github.com/dotnet/source-build/pull/910 as failure to apply patches: https://dnceng.visualstudio.com/public/_build/results?buildId=47321&view=logs. The failure log might go away when I retry it.

Fix Windows build: clean submodules

---

repos/dir.targets
repos/known-good.proj

> Detects new packages after each repo and prints a hopefully useful error if none were produced.
>
> As a side benefit, stop printing the entire package version props file before every single repo: instead, print the list of package identities each build produced.
The big benefit is catching silent failures in CI and local builds. There might still be a way for a silent failure to happen that leaves partial packages available--detailed baselining would fix this, but we would have to carefully maintain it (investigate whether a change is "real"). I don't see enough value to do that now.
Users who try to `git clone ; build ; [make changes]; build` (fine for normal repos, but we don't support incremental builds) will hit this error, so I tried to make the message actionable.
Example:
``` …
```

Assert each build produces packages

---

tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Baseline generation now includes `IsDirectDependency`, but our baseline for 2.1.6 doesn't have that attribute. This means a diff between 2.1.6 and some future 2.1.7 would show a bunch of noisy `IsDirectDependency` additions.
To allow a noiseless diff, update the baselines so they include the new attribute. This PR doesn't add or remove any packages, so it still has the same package id/versions as the 2.1.6 baseline.
Once 2.1.7 comes out, instead of diffing from 2.1.6 to 2.1.7, diff from this PR's commit to 2.1.7 to see only the package adds/removes.

[release/2.1] Update prebuilt baselines: add IsDirectDependency

---

tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Update `release/2.2` baselines with no package adds/removes for the same reasons as https://github.com/dotnet/source-build/pull/914.

[release/2.2] Update prebuilt baselines: add IsDirectDependency

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/ci-linux.yml
build.proj
dir.props
repos/dir.targets
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection.csproj
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/Microsoft.DotNet.SourceBuild.Tasks.csproj
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/UsageReport/WriteUsageBurndownData.cs

Generates burndown data from the prebuild report data checked in to git.  The burndown data counts the number of prebuilt packages and versions and number of prebuilt packages alone.

Add task to generate burndown data from the prebuilt report

---

build.proj

Disassembling the packages takes some time, is noisy, and isn't necessary in a production build that doesn't produce a tarball. This change only disassembles ref-only packages when creating a tarball.
I used this change while working on the 3.0 preview update to save some time. This PR pulls it out to add to all branches.

Only disassemble ref packages to create tarball

---

repos/dir.targets

This ensures patches apply even when building the tarball inside a git repo. Without `--work-tree`, the apply command finds the ancenstor `.git` and uses it as the root for relative paths, causing a patch skip.

Add "work-tree" parameter to git apply to unblock tarball builds within a git repo

---

dir.props
repos/application-insights.proj
repos/cli.proj
repos/dir.targets
repos/netcorecli-fsc.proj
repos/newtonsoft-json.proj
repos/nuget-client.proj
repos/roslyn.proj
repos/templating.proj
repos/xliff-tasks.proj
tools-local/init-build.proj

Instead of custom verbosity levels for each project/build, use a standard logging verbosity level everywhere. This lets us enable detailed logging everywhere, or have consistently smaller logs.
To override, use:
/p:LogVerbosity=quiet|minimal|normal|detailed|diagnostic
as a build argument to the main build script.
Comparing the build logs before and after this change, I didn't spot any noticeable change in the default logging verbosity, with one exception:
The logging level of the 'cli' project the has been reduced from `detailed` to `minimal` to match the logging level used everywhere else.
(The reason I would like to include this is change is so that I can bump up the logging verbosity in my local builds. The build logs can then be (hopefully) used by static analysis tools to figure out …

Use consistent logging verbosity everywhere

---

tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/CheckForPoison.cs

- Add scss extension.
- Fix RunCsc and RunVbc not getting detected due to casing.

Add a couple more exclusions to poison report.

---

init-tools.sh

This is based on the platfrm selection logic from coreclr.
Instead of trying to run x64 executibles on non-x64 platforms, this forces the download of the platform-appropriate dotnetcli and then uses that.
This commit also doesn't actually fix builds on any platform. It just gets buildtools running on additional platforms. Depending on the platform, things will still fail.

Update init-tools to handle additional architectures

---

dependencies.props
repos/cli.proj

This will also be used for all future releases.  Currently these must be manually updated with the correct versions each release, but we hope to automate these updates in the future.

Add parameters for the 1.0,  1.1, and 2.1 builds shipping at the same time as the 2.2.3 release.

---

dependencies.props
repos/cli.proj

These will also be used for every future release.  Currently these are manually updated each release, but we want to eventually get the versions numbers published somewhere we can automatically update them.

Add parameters for the 1.0 and 1.1 builds shipping at the same time as the 2.1.9 release.

---

Documentation/SourceBuildPrebuiltRepoStatus.md

The repo should not actually have been removed. See #994. I've reopened #895

Reset templating pre-built status

---

.gitmodules
repos/core-setup.proj

* Add git commit count and hash in core-setup proj
Fixes #741
* Use reflexive `.` to set tracking branch same as in the current repo - [docs](https://git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-submoduleltnamegtbranch)
* This only affects when we update with remote (without `cd`ing into directories one at a time), i.e.
`git submodule update --remote`

 Add git commit count and hash in core-setup proj 

---

eng/Version.Details.xml
eng/Versions.props

Auto-update didn't happen for this build.  Opening manually for build 20190709.1 
https://dev.azure.com/dnceng/internal/_build/results?view=results&buildId=257275

[release/3.0] Update dependencies from dotnet/source-build-reference-packages

---

eng/Version.Details.xml

When I had the option of something higher or lower in the graph, I went with higher - this keeps the dependency chains shorter since core-sdk or toolset depend on most things.  `core-sdk` is still a placeholder - I need to implement the workaround since core-sdk only publishes blobs, not packages.

Add coherency info to Version.Details.xml.

---

repos/roslyn.proj

NGEN optimization is not enabled when building from source.
See
https://github.com/dotnet/arcade/blob/a1805103791e43031355e11c0d037bca803a9593/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L68
https://github.com/dotnet/arcade/blob/a1805103791e43031355e11c0d037bca803a9593/src/Microsoft.DotNet.Arcade.Sdk/tools/Imports.targets#L27
Roslyn is being fixed to use the right conditions: https://github.com/dotnet/roslyn/pull/37327

Remove ApplyNgenOptimization settings

---

patches/corefx/0003-Rename-OfflineBuild-property-to-DotNetBuildOffline.patch

Adding patch to fix corefx property name from OfflineBuild to DotNetBuildOffline and to update the target to build correctly.  From https://github.com/dotnet/corefx/pull/39979

Fix corefx property name

---

patches/core-sdk/0001-Exclude-test-project-from-source-build.patch
patches/core-sdk/0002-Allow-separate-core-setup-and-ASP.NET-RIDs.patch
repos/core-sdk.proj
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

- This patches core-sdk to allow different RIDs for the core runtime and ASP.NET runtime.
- We also go back to building CoreCLR and CoreFX as non-portable to support the non-portable core-setup.
So far I've only tested the default non-portable build on my Fedora 31 machine, but that builds and smoke-tests.  I'll work on testing additional configurations.

Return to building core runtime as non-portable and allow different portability in ASP.NET and core runtime

---

patches/aspnet-extensions/0006-Do-not-build-.NET-Fx-binaries-in-source-build.patch

aspnet-extensions
Just one binary in this PR. The other 2 that I originally modified in a previous PR are not needed anymore.

Do not build .NET Fx binaries in source build

---

patches/aspnet-xdt/0002-Do-not-build-NET-Fx-binaries-in-source-build.patch

Removing a single NET Fx binary in source build

Do not build for NET Fx in source build - aspnet-xdt repo

---

patches/nuget-client/0006-Do-not-build-NET-Fx-binaries-in-source-build.patch

Stops building all NET Fx binaries in source-build.
VS Code tests passed without any issues.

Do not build NET Fx binaries in source build - nuget-client

---

patches/arcade/0004-Import-PackageVersions-props-if-exists.patch
patches/arcade/0005-Update-SystemNetHttpPackageVersion.patch
repos/arcade.proj

Use the PVP with previously source-built versions for MicrosoftCodeAnalysisCSharp versions only in arcade.  Update System.Net.Http version to reference package version.

Use PVP for MicrosoftCodeAnalysisCSharp versions in arcade

---

patches/core-sdk/0003-Don-t-add-target-rid-to-NetCoreRuntimePackRids.patch

Attempt to fix https://github.com/dotnet/source-build/issues/1202.
I haven't tested this because `./build.sh` on `release/3.0` is failing for me: https://github.com/dotnet/source-build/issues/1230.
CC @crummel @dagood @omajid @dsplaisted @nguerrera

Don't add target rid to NetCoreRuntimePackRids

---

.vsts.pipelines/jobs/ci-linux.yml

Make the timeout 40 minutes - they usually take 30 when successful but have been hanging to three hours.  Also turn continueOnError on so if they timeout the build will keep going.

Work around hanging unit tests.

---

build-source-tarball.sh

Packages that are supplied to source-build via the source-built or reference package archives may show up in IL src when we decompile reference only packages.  These can be removed from the IL src since they are being resolved from the archives.

Remove il src from tarball for packages that are in source-built or refpkg archives

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-local.yml
.vsts.pipelines/steps/init-submodules.yml
.vsts.pipelines/steps/publish-prebuilt-data-sh.yml
.vsts.pipelines/steps/setup-macos-native.yml

The `du` call after the build scripts were masking the exit code, exit early if the build fails.

Make builds that fail actually fail CI.

---

patches/msbuild/0005-Remove-runtime-identifiers-to-break-runtime-prebuilt.patch

Runtime identifier is not needed in core build and therefore, not in source-build.  This specification is pulling in runtime.win-x*.nupkg prebuilts.

Add patch to remove runtime identifier specification in msbuild

---

patches/vstest/0005-Remove-runtime-identifier-from-vstest-projects.patch

Runtime identifier is not needed in core build and therefore, not in source-build. This specification is pulling in runtime.win-x*.nupkg prebuilts.

Add patch to remove runtime identifier specification in vstest

---

repos/package-source-build.proj
src/package-source-build/package.proj

Pass in the package versions props file to include in the source-built artifacts tarball rather than trying to calculate it in the project.

Include the correct package version props file when building offline

---

patches/roslyn/0005-Remove-System.Runtime.Loader-hack.patch

This change removes RoslynTools.Lightup.System.Runtime.Loader prebuilt.
It is the same change as the change implemented in Roslyn repo, see commit: https://github.com/dotnet/roslyn/commit/3e9505e9b430c852bc36579647c5951b4a808316

Remove RoslynTools.Lightup.System.Runtime.Loader prebuilt - Roslyn repo

---

repos/aspnetcore.proj

AspNetCore's build script (build.sh) builds eng/tools/RepoTasks before building the main project.  The build of this project doesn't use the passed in build params from source-build.  This change set DotNetPackageVersionPropsPath in env variables so the RepoTasks build can pick up the SourceBuilt version of Microsoft.Net.Compilers.Toolset.

Add PackageVersionProps to env variables

---

repos/corefx.proj

Update corefx project to set property to build all packages.  After the merge of #1237, corefx in source-build stopped building all packages.  With the latest update to corefx brought in by #1237, building all packages is gated by the BuildAllPackages property here: https://github.com/dotnet/corefx/blob/c1778515a3bee34cc09c757b5563d0af0c8b1e99/src/packages.builds#L8-L12

Set BuildAllPackages in corefx

---

patches/coreclr/0002-Conditionally-override-PackageVersion-properties.patch

When building System.Private.CoreLib.dll in coreclr, dependencies.props is imported after PackageVersionProps when an override is provided.  This patch allows dependencies.props to not override the PackageVersionProps versions and therefore skip the source-built versions.  It appears that there is work ongoing to fix this.  See https://github.com/dotnet/coreclr/pull/25596

Conditionally override PackageVersions in coreclr

---

repos/templating.proj
tools-local/prebuilt-baseline-offline.xml

Without this, the Templating repo loads Microsoft.NETcore.App.Host.linux-x64 during bootstrapping.

Set property in Templating build to not use AppHost

---

smoke-test.sh

OSX requires the `dotnet` being used to be on the path, or else it won't find the runtime.
Fixes #1344.

Set PATH for OSX as well as DOTNET_ROOT.

---

build-source-tarball.sh
dir.props
patches/aspnetcore/0001-Don-t-call-dotnet-without-path.patch
patches/aspnetcore/0002-Use-non-portable-NETCoreAppRuntime-for-crossgen.patch
patches/aspnetcore/0003-Conditionally-set-PackAsToolShimRID.patch
patches/aspnetcore/0004-Exclude-analyzer-for-source-build.patch
patches/aspnetcore/0005-Import-PackageVersions.props.patch
patches/aspnetcore/0006-Exclude-some-projects-from-source-build.patch
patches/aspnetcore/0007-Fix-version-number.patch
patches/aspnetcore/0008-Remove-Yarn-dependency-not-used-in-source-build.patch
patches/aspnetcore/0009-TargetFramework-changes.patch
patches/aspnetcore/0010-Revert-to-reference-versions-of-source-built-package.patch
patches/aspnetcore/0011-Add-FreeBSD.patch
patches/aspnetcore/0011-Support-global.json-on-arm64-as-well.patch
patches/aspnetcore/0012-Support-building-for-arm64-on-arm64-nix.patch
patches/aspnetcore/0012-Support-global.json-on-arm64-as-well.patch
patches/aspnetcore/0013-Support-building-for-arm64-on-arm64-nix.patch
patches/core-sdk/0003-Enable-building-on-arm64-machines.patch
patches/core-setup/0004-Enable-building-for-arm64-on-arm64.patch
patches/corefx/0004-Enable-build-on-hosted-arm64.patch
repos/aspnetcore.proj
repos/core-sdk.proj
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
repos/known-good.proj
tools-local/init-build.proj

With this change, I can build source-build on RHEL 8 on arm64:
```
$ ~/source-build/dotnet-sdk/dotnet --info                                                                                                                                                                      
.NET Core SDK (reflecting any global.json):                                                                                                                                                                                                   
Version:   3.0.100                                                                                                                                                                                                                           
Commit:    04339c3a26 …
```

Enable building on arm64

---

patches/roslyn/0001-Conditionally-remove-net472-from-TargetFrameworks.patch
patches/roslyn/0002-Don-t-install-2.1.503-for-testing.patch
patches/roslyn/0003-.NET-Core-only-for-VBCSCompiler.patch
patches/roslyn/0004-Do-not-build-NET-Fx-binaries-in-source-build.patch
patches/roslyn/0005-Import-PackageVersions-props-if-exists.patch
patches/roslyn/0006-Get-rid-of-analyzers.patch
patches/roslyn/0007-Include-Compilers-package-projects-in-source-build.patch

Microsoft.NETCore.Compilers and Microsoft.Net.Compilers.Toolset packages were not being produced when building roslyn in source-build.  This patch enables roslyn to produce these packages.

Build Compilers packages in roslyn

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-local.yml
eng/Version.Details.xml
tools-local/init-build.proj

- Remove init-submodule steps - this breaks with internal-only builds and is no longer applicable.
- Pass in AzDo's PAT for cloning source repos.
- Add `<RepoName>` tags for the repos we have serviced in the past.
- In addition to this, specifically only for repos we actually service, we will have to add `<SourceDirectory>` tags to their repo.projs à la [ASP.NET-Extensions](https://github.com/dotnet/source-build/blob/7ec46364487c3b458d64651f598685a8cd512554/repos/aspnet-extensions.proj#L3).  I'm trying to figure out a way around this but I'm not sure we can do it without quite a bit of hackery.

Some changes to support internal builds

---

patches/core-sdk/0001-Don-t-call-dotnet-without-a-path.patch
patches/core-sdk/0002-Patch-property-used-for-core-setup-version.patch
patches/core-sdk/0003-Enable-building-on-arm64-machines.patch
patches/core-sdk/0004-Exclude-test-folder-from-SourceBuild.patch
patches/core-sdk/0005-Use-variable-source-build-sets-for-ASP.NET.patch
patches/core-sdk/0006-Remove-debian-package-generation.patch
patches/core-sdk/0007-Don-t-set-SourceLinkVersion-in-core-sdk.patch
patches/msbuild/0001-Don-t-call-dotnet-without-path.patch
patches/msbuild/0002-Remove-runtime-identifiers-to-break-runtime-prebuilt.patch
patches/msbuild/0003-Use-source-built-version-of-SystemResourcesExtension.patch

Patches for two issues that were preventing the final sdk build from completing:
1. Make msbuild use the source built version of System.Resources.Extensions
2. Don't set the source-link version in core-sdk, get it from arcade

Fixes to allow tool bootstrapping to succeed

---

support/additional-prebuilts-to-delete.txt

We delete the x64 variants of the prebuilts, but not arm64 variants. When source-build is compiled on arm64, the presence of those prebuilts causes the tarball-construction (through ./build-source-tarball.sh) to fail.
Fix that by handling the arm64 prebuilts exactly like the x64 prebuilts.
Fixes #1409

Delete arm64 variants of prebuilts too

---

patches/sourcelink/0002-Patch-ref-packages-out.patch
patches/sourcelink/0005-Update-targets-to-support-netcoreapp2.1.patch

The bootstrap final build is failing because the bootstrapped stage1 SDK version of Microsoft.Build doesn't support netcoreapp2.0.  Updating sourcelink tasks to build with the stage1 SDK

Update sourcelink tasks to build for netcoreapp2.1

---

support/additional-prebuilts-to-delete.txt
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/CopyReferenceOnlyPackages.cs

Some template packages we use erroneously include .cache files, which are text like:
```
{
"version": 1,
"dgSpecHash": "vODEZsXQI5BwPuuSe1Hzd5XIVnUkcaoRo2EnUbZriP5/DirtEEti1rvaejH0cCazlJ03IjAsmHvbrSO0i7iwaQ==",
"success": true
}
```
so aren't detected as binary files by the reference-package disassembly and assembly.  These have no real effect but it's more correct to skip them.
Fixes #1438.

Add *.cache to excluded files when copying ref packages.

---

patches/core-sdk/0006-Add-target-rid-to-AppHostRuntimeIdentifiers.patch

Fixes https://github.com/dotnet/source-build/issues/1444 for 3.0
cc @nguerrera @dagood @crummel @omajid @dseefeld

core-sdk: Add target rid to AppHostRuntimeIdentifiers

---

.vsts.pipelines/jobs/ci-linux.yml
build-source-tarball.sh
build.proj
dir.props
support/tarball/build.sh
tools-local/init-build.proj

Distro maintainers will want to use their own builds of the source-build-reference-packages and previously-built-packages instead of using our prebuilt tarballs.  This changes the tarball production script and tarball build to support that.
Fixes #1436.

Allow user to skip downloading the previously-source-built packages and supply their own.

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-linux_bootstrap.yml
.vsts.pipelines/steps/run-bootstrap.yml
dir.props
eng/Version.Details.xml
repos/core-setup-portable.proj
repos/core-setup.common.props
repos/core-setup.common.targets
repos/core-setup.proj
repos/coreclr-portable.proj
repos/coreclr.common.props
repos/coreclr.proj
repos/corefx-portable.proj
repos/corefx.common.props
repos/corefx.common.targets
repos/corefx.proj
repos/known-good.proj

This allows somebody to build source-build and create portable projects offline in addition to non-portable.  It also makes life easier for bootstrapping, as the portable bits serve as a fallback for all RIDs.
- Copy `coreclr.proj`, `corefx.proj`, and `core-setup.proj` to create additional portable versions that are included as references in the non-portable Linux builds.  These are just always forced to portable.
- Add extra entries to Version.Details.xml.  These don't create extra source directories because the repo URLs are the same for both entries, so we build the portable versions first, copy any packages with `linux` in the name, then delete `artifacts` and `bin` folders, which seems to work reasonably well to reset the repo.

Always build portable runtime in addition to non-portable.

---

build-source-tarball.sh
build.sh
dir.props
support/tarball/build.sh

Allow users to supply their own SDK for bootstrapping

---

build-source-tarball.sh
eng/Versions.props

These should come from previously source built archive instead.

Remove copy of coreclr-tools to tarball

---

.vsts.pipelines/jobs/ci-linux.yml
eng/Version.Details.xml
tools-local/prebuilt-baseline-online.xml

Feb 3.1 Update coreFX

---

.vsts.pipelines/jobs/ci-linux_bootstrap.yml
.vsts.pipelines/steps/run-bootstrap.yml
smoke-test.sh
support/tarball/tool-bootstrapping/bootstrap.sh

Recently, source-build and s-b-r-p updated build.sh to take parameters for source-built artifacts, sdk and reference-packages.  This PR updates the bootstrap script to work with these changes, rather than copying things around manually.

Update bootstrap scripts to use params for source-build  and s-b-r-p build.sh

---

repos/dir.targets
tools-local/generate-graphviz.proj
tools-local/generate-graphviz/generate-graphviz.proj

I wrote this quick project while investigating putting source-build into Arcade (https://github.com/dotnet/source-build/issues/1466) and into the Microsoft official builds, to look for leaves and any chunky areas. I ran it with this command line on Windows:
```
.\eng\common\build.ps1 -build -projects C:\git\source-build\tools-local\generate-graphviz.proj /bl /p:TargetRid=win-x64 /p:GraphVizDir=C:\tools\graphviz\2.38\bin
```
Produces output like this:
(You can also use a tool like http://webgraphviz.com/ with the `graphviz.dot` output.)
Doesn't run during builds.

Add GraphViz dependency graph generator project

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/ci-linux.yml
dir.props
eng/Versions.props
repos/coreclr.common.props

We have had some issues building in RHEL 8, so lets set up a CentOS 8 CI system to try and catch those issues earlier.

Add CentOS 8 CI build

---

Directory.Build.props
build.proj
tools-local/tasks/Directory.Build.props
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs

In local tests, my average download speed seems to either be `~4,621.04 kB/s` or `~19,680.66 kB/s`, not really anything in between. I suspect we might be hitting something similar in CI causing the timeouts, just extremely low download speed at some certain chance.
To adjust the timeout or turn it off, use props like:
```
/p:DownloadSourceBuildReferencePackagesTimeoutSeconds=N/A
/p:DownloadSourceBuiltArtifactsTimeoutSeconds=N/A
```
Also include a fix (and simplification) for Visual Studio sb task authoring.
The idea/reasoning for a hang-detecting extra timeout comes from https://github.com/dotnet/core-setup/pull/6168#discussion_r279428268.
Example console output:
```
DownloadFileSB timeout set to 00:10:00
DownloadFileSB.Downloading …
```

Add DownloadFileSB timeout and progress logging

---

Documentation/planning/arcade-powered-source-build/implementation-plan.md

@dseefeld Here are the changes in the docs to reflect what's going on in aspnetcore in 5.0.
extensions consolidation occurred in preview2 and portions moved to dotnet/runtime and dotnet/aspnetcore according to the docs https://github.com/aspnet/Announcements/issues/411
aspnetcore-tooling consolidation occurred in preview6 and moved to dotnet/aspnetcore

Repo consolidation updates for aspnetcore

---

scripts/compare-builds.sh
scripts/fetch-microsoft-sdk.sh
smoke-test.sh

This should let us catch surprises in releases.
Here's the current output of this script when comparing my local `/usr/lib64/dotnet` (source-build, 3.1.103) with `~/local/dotnet-sdk-3.1.103` (Microsoft's build, downloaded from dot.net):
https://gist.github.com/omajid/9111a9310d452b3594b770d4ca8a3d87
A couple of questions:
0. Does this seem useful?
1. Do we want to run this manually at release time? Is there a release-checklist I should edit?
2. Is the output useful in its current form? Should I be filtering out more or fewer things?
3. Do we want to hook this into CI? And somehow flag any changes to the expected diff? If that's the case, how do we want to handle file version differences?

WIP: Add a test to compare two SDK and show file diff

---

README.md

Some users were asking about this on gitter channels. I figured it should be documented in the "obvious" location.
cc @dagood

Include the build location in README

---

smoke-test.sh

Before this change, running smoke tests on arm64 using:
./build.sh
./build.sh --run-smoke-test
fails with an error that looks like this:
cat: source-build/artifacts/obj/x64/Release/TargetInfo.props: No such file or directory
It turns out that smoke-test.sh hardcodes `x64` throughout. Fix that by checking the current architecture (using `uname -m` and `uname -p`) and then using that instead of hardcoded `x64`.

[release/3.1] Fix smoke-test.sh to work on arm64

---

support/tarball/smoke-testNuGet.Config

This file was added at the beginning of the 3.1.106 release process (https://github.com/dotnet/source-build/pull/1663) and removed at the end, to deal with authed sources. The removal was intended as a way to keep `/smoke-testNuGet.config` and `/support/tarball/smoke-testNuGet.config` in sync over time (we'd create a new copy from the main one when we need it), but the release process is simpler if we just keep both copies even when they're identical. We don't expect significant drift with these files in the servicing branch anyway.
https://github.com/dotnet/source-build/issues/1669 tracks a better approach that will let us remove this file altogether.

Add persistent support/tarball/smoke-testNuGet.Config

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
.gitignore
Documentation/servicing/tagging.md
Documentation/servicing/update-2.1.md
Documentation/servicing/update-3.1.md

Update the release checklist based on my experience with 3.1.106/2.1.516 servicing. I split out some details into docs with absolute links to keep it manageable but still capture everything that seems important without referring to internal docs.
Fixes https://github.com/dotnet/source-build/issues/1632, "Add Microsoft SDK vs. source-built SDK file list diff smoke-test review to release checklist"

Release checklist updates post 3.1.106/2.1.516

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/prepare-artifacts.yml
scripts/fetch-azdo-artifact-tarball.sh

Add a simple prepare-artifacts job to take over manual work preparing previously-source-built tarballs.
Fix up the AzDO fetch script: simplify and document for the scenario it's actually used for: downloading onto fresh machines for manual testing.
---
I worked on this to avoid manual steps for 3.1.106, and polished it a little more for this PR for next time.
Fixes https://github.com/dotnet/source-build/issues/1676

Add prepare artifacts job; fixup AzDO fetch script

---

build.sh

For https://github.com/dotnet/source-build/issues/1646
Download links with this change:
https://github.com/dagood/source-build/archive/49195585d0de06e9a06b8fb005c460035363b2af.zip
https://github.com/dagood/source-build/archive/49195585d0de06e9a06b8fb005c460035363b2af.tar.gz

Run "git init" when .git doesn't exist to help GitHub source zip/tar.gz builds

---

.vsts.pipelines/jobs/ci-linux_bootstrap.yml

See https://github.com/dotnet/source-build-reference-packages/pull/137
Removing this branch reference is tracked by https://github.com/dotnet/source-build/issues/1498

Update 'release/3.1' => 'pre-arcade' SBRP branch in bootstrap CI

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-local.yml

I wanted to take previously source-built artifacts from https://dev.azure.com/dnceng/internal/_build/results?buildId=807228&view=results, but the macOS leg failed due to auth issues. The auth json looks like this, literally, and gets a 401:
```json
...
{
"endpoint":"https://pkgs.dev.azure.com/dnceng/_packaging/dotnet3.1-internal-transport/nuget/v3/index.json",
"username":"optional",
"password":"$(dn-bot-dnceng-artifact-feeds-rw)"
}
...
```
This is because `dn-bot-dnceng-artifact-feeds-rw` is not defined in that particular build definition. AzDO leaves the entire variable substitution expression when it doesn't match any varaible, then we pass it in directly:
```yaml
InternalPackageFeedPatEnv: $(dn-bot-dnceng-artifact-feeds-rw)
...
- bash: ...
env:
internalPackageFeedPat: …
```

[release/3.1] Fix macOS PAT flow for internal non-authenticated builds

---

patches/installer/0005-Don-t-do-this-in-source-build-aspnetcore-targeting-p.patch
patches/runtime/0018-Don-t-include-extra-PackageIcon-Arcade-does-this-alr.patch
tools-local/prebuilt-baseline-online.xml

Portable build: Patch runtime to not include extra package icon in nupkgs.
OSX: Patch installer to not generate extra packages that require the aspnetcore-targeting-pack.tar.gz that aren't produced in source-build.  I checked and neither 3.1 nor 5.0 preview4 produced these, so this is a new requirement and the OSX build passes smoke-tests locally without it.

Fix a couple CI issues leftover from preview8

---

Documentation/planning/arcade-powered-source-build/implementation-plan.md

I don't think a dev branch is required, we can work in `main`/`master`.
Even if we don't have a dev branch, CI shouldn't break at any point along the way... the patches we apply should work against the repo's ordinary CI and build. Then when the source-build PR validation job and official build gets added, it should still work. Then whether we do a mock official build or an actual official build, it's all the same to us.

Remove dev branch as up-front step required by arcade-powered source-build plan

---

Documentation/planning/arcade-powered-source-build/implementation-plan.md

For xliff-tasks, @wli3 is the loc champion, driving more features and resolving missing features. However, core-eng owns xliff-tasks infrastructure maintenance. Since the arcade-powered source-build work is infra work, core-eng should be the point of contact: @markwilkie.
The shared ownership also came up earlier at https://github.com/dotnet/xliff-tasks/pull/352#issuecomment-677788203 to unblock Arcade updates into xliff-tasks.

Make xliff-tasks owner Mark Wilkie: core-eng maintains repo's infra

---

tools-local/prebuilt-baseline-online.xml
tools-local/tasks/Directory.Build.props
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UsageReport/UsageData.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UsageReport/UsagePattern.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UsageReport/UsageValidationData.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UsageReport/ValidateUsageAgainstBaseline.cs
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UsageReport/WriteUsageReports.cs

This ports the flexible baseline feature from https://github.com/dotnet/arcade/pull/6155 back to dotnet/source-build. This makes servicing updates a bit more sustainable by removing the need to *always* update the online baseline even if the changes are expected and predictable. See https://github.com/dotnet/source-build/issues/1726.
I reverted some changes because dotnet/source-build works a little differently. E.g. here, warnings are allowed, and we always know where the baseline is located.
Also, yet another tweak to make VS work for editing the task project. The `*` wildcard wasn't evaluating properly with the last attempt because it was put directly into item metadata--now it's simpler.

[release/3.1] Add flexible baseline patterns: avoid updating online baseline with each release

---

repos/known-good.proj

Re-enable package-source-build project to generate previously source-built tarball.

Re-enable packaging source-build

---

patches/coreclr/0005-Fix-bad-configure-tests.patch

See: #1744
This is a backport of the fix that was merged into runtime for master: https://github.com/dotnet/runtime/pull/42756

Fix 'elf.h' file not found on macOS 10.15

---

.vsts.pipelines/builds/ci-internal.yml
.vsts.pipelines/builds/ci.yml
.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/stages/prepare-artifacts.yml
.vsts.pipelines/stages/stage-jobs-matrix.yml

(cherry picked from commit f08ac8a5aaffd3936f5b7c64e925118d9190dfc3)
```
#	.vsts.pipelines/builds/matrix.yml
#	.vsts.pipelines/jobs/ci-linux_bootstrap.yml
#	.vsts.pipelines/steps/run-bootstrap.yml
```

[release/2.1] Use one stage per job in CI

---

Documentation/planning/arcade-powered-source-build/onboarding/README.md
Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md
Documentation/planning/arcade-powered-source-build/onboarding/local-onboarding.md

Rendered: https://github.com/dagood/source-build/tree/apsb-ci-doc/Documentation/planning/arcade-powered-source-build/onboarding

Add doc describing arcade-powred source-build CI onboarding and eng/ config

---

patches/installer/0007-Don-t-restore-WinForms-and-WPF-templates-for-source-.patch
tools-local/prebuilt-baseline-offline.xml

These are already not included in non-Windows builds but are still restored.

Patch installer to not restore WPF and WinForms templates.

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-local.yml
build.proj

Also remove unnecessary download in ci-local. (Not building tarball.)
For https://github.com/dotnet/source-build/issues/1658

[3.1] Only set download timeout in CI

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-local.yml
build.proj

Also remove unnecessary download in ci-local.
For https://github.com/dotnet/source-build/issues/1658
(cherry picked from https://github.com/dotnet/source-build/pull/1799)
> Conflicts:
>	.vsts.pipelines/jobs/ci-local.yml
(It looks like we missed porting auth setup to `master` at some point.)

[master] Only set download timeout in CI

---

.vsts.pipelines/stages/prepare-artifacts.yml

Prepare Artifacts downloads artifacts from a portable job, but doesn't have a stage dependency on it. The timing's been working out by chance so far but we should fix this.

[release/3.1] Fix prepare-artifacts portable dependency

---

.vsts.pipelines/builds/matrix.yml

This makes it easier to tell when PR validation succeeds.
(It also removes the risk of someone doing a bad PR merge if a real error is mistaken for the known macOS failure, but this isn't IMO very significant for our small team vs. a repo like dotnet/runtime where it matters much more.)
Fixing is tracked by https://github.com/dotnet/source-build/issues/1819

Disable macOS CI temporarily

---

eng/Version.Details.xml
eng/Versions.props

Update reference to source-build-reference-packages to pick up latest packages from https://github.com/dotnet/source-build-reference-packages/pull/170.

Update to latest version of SBRP

---

eng/Version.Details.xml
repos/aspnetcore.proj
repos/cssparser.proj
repos/known-good.proj

This repo produces the Microsoft.Css.Parser nuget package which is used by aspnetcore.
dotnet/cssparser is licensed under MIT. It does not use arcade, so the build project is based off of application-insights.proj.
After this fix, a local tarball build results in the removal of this line from the annotated prebuilt xml:
<AnnotatedUsage Id="Microsoft.Css.Parser"
Version="1.0.0-20200708.1"
File="src/aspnetcore.a4938d07a5127ffad8466ddf703a6b5b21f4b0c9/artifacts/obj/Microsoft.AspNetCore.Razor.Tools/project.assets.json"
IsDirectDependency="true"
IsAutoReferenced="true"
Project="src/aspnetcore.a4938d07a5127ffad8466ddf703a6b5b21f4b0c9/"/>

Add dotnet/cssparser repo and build it from source

---

patches/roslyn/0008-remove-RichCodeNav.EnvVarDump-on-source-build.patch

should eliminate RichCodeNav.EnvVarDump
@crummel ptal
cc @omajid

roslyn: remove RichCodeNav.EnvVarDump on source-build

---

eng/Version.Details.xml
patches/diagnostics/0001-Dont-build-analyzers-for-source-build.patch
repos/diagnostics.proj
repos/vstest.proj

This produces the Microsoft.Diagnostics.NETCore.Client package that's
shipped as part of the Microsoft SDK too.
Adding this also adds some additional dependencies:
<AnnotatedUsage Id="Microsoft.NETCore.DotNetAppHost" Version="2.1.0" File="src/diagnostics.b6de9d322756aed892dafa0aed0053caa7db4fa6/artifacts/obj/Microsoft.Diagnostics.NETCore.Client/project.assets.json" Project="src/diagnostics.b6de9d322756aed892dafa0aed0053caa7db4fa6/" SourceBuildPackageIdCreator="runtime MicrosoftNETCoreDotNetAppHostPackageVersion/5.0.0-preview.8.20407.11" />
<AnnotatedUsage Id="Microsoft.NETCore.DotNetHostPolicy" Version="2.1.0" File="src/diagnostics.b6de9d322756aed892dafa0aed0053caa7db4fa6/artifacts/obj/Microsoft.Diagnostics.NETCore.Client/project.assets.json" …

Add dotnet/diagnostics to source-build

---

eng/Version.Details.xml
patches/symreader/0001-Add-initial-Arcade-SDK-switchover.patch
patches/symreader/0002-Fix-license-per-Arcade-SDK-expectations.patch
repos/runtime.proj
repos/symreader.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Add the symreader repo back to the build to build the `Microsoft.DiaSymReader/1.3.0` dependency from source.
This is an old package with 2.1 era infra that I upgraded, from repo toolset to arcade.
For https://github.com/dotnet/source-build/issues/1812.

Add symreader to source-build for Microsoft.DiaSymReader/1.3.0

---

tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/PublishCoreSetupBinaries.cs

./build.sh was failing to build on arm64 because we were placing the runtime tarball at:
./artifacts/obj/arm64/Release/blobs/Runtime/$VERSION-arm64/dotnet-runtime-$VERSION-$RID.tar.gz
And the extra -arm64 in `$VERSION-arm64` under the Runtime directory was screwing up the build.
Adding -arm64/.arm64 in the expression list makes things work.
The fix was suggested by @dagood.

Fix building on arm64

---

patches/runtime/0026-Update-nuget-versions-to-version-in-SBRP.patch
tools-local/prebuilt-baseline-online.xml

Update RefOnlyNuget*Versions to use 5.1.0 rather than 4.9.4, since 5.1.0 already exists as a reference package in source-build-reference-packages

Update runtime nuget version to SBRP version

---

Documentation/planning/arcade-powered-source-build/implementation-plan.md

We've added some repos for 5.0 GA. We need to track these for arcade-powered source-build. I haven't looked into ownership yet for these ones, but we can at least add them to the table now for easy reference.

Add repos added for 5.0 GA to table

---

Documentation/planning/arcade-powered-source-build/implementation-plan.md

Adding @jmarolf as the point of contact for arcade-powered source-build for https://github.com/dotnet/roslyn-analyzers.
(/cc @mavasani)
I'm leaving the repo's tier as `?` for now because we don't quite yet have it implemented in `master` for 5.0. Could probably figure it out but there's no need at the moment.

Add roslyn-analyzers owner to arcade-powered source-build implementation plan

---

patches/runtime/0027-Remove-libraries-packages.proj-harvesting.patch

Conditionally remove the import of `restore\harvestPackages.targets` to remove some PackageDownload elements bringing in prebuilts.
For https://github.com/dotnet/source-build/issues/1844.

Stop harvesting packages in runtime: remove prebuilts

---

patches/command-line-api/0004-Exclude-System.CommandLine.Hosting.patch

From the annotated report in a GA build, this seems to be the only user of:
```
<AnnotatedUsage Id="Microsoft.Extensions.Configuration" Version="2.2.0" File="src/command-line-api.afd010ba8cb3cbd714c734465d1a5de1ee133e2d/artifacts/obj/System.CommandLine.Hosting/project.assets.json" Project="src/command-line-api.afd010ba8cb3cbd714c734465d1a5de1ee133e2d/" SourceBuildPackageIdCreator="runtime MicrosoftExtensionsConfigurationPackageVersion/5.0.0" />
<AnnotatedUsage Id="Microsoft.Extensions.Configuration.Abstractions" Version="2.2.0" File="src/command-line-api.afd010ba8cb3cbd714c734465d1a5de1ee133e2d/artifacts/obj/System.CommandLine.Hosting/project.assets.json" Project="src/command-line-api.afd010ba8cb3cbd714c734465d1a5de1ee133e2d/" SourceBuildPackageIdCreator="runtime …
```

Exclude System.CommandLine.Hosting from source-build

---

eng/Versions.props
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Upgrade previously-source built to `0.1.0-5.0.100-877538` (https://dev.azure.com/dnceng/internal/_build/results?buildId=877538&view=results, ccde1aa) and update the baselines.
For https://github.com/dotnet/source-build/issues/1865

Update previously-source-built tarball and prebuilt baselines

---

patches/roslyn/0011-Build-Microsoft.CodeAnalysis-for-source-build.patch

It's needed by roslyn-analyzer.
Fixes #1870

Enable Microsoft.CodeAnalysis in roslyn

---

patches/vstest/0007-Use-Microsoft.Diagnostics.NETCore.Client-from-PVP.patch
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

We build `Microsoft.Diagnostics.NETCore.Client/0.2.0` thanks to https://github.com/dotnet/source-build/pull/1824. Add a patch to dotnet/vstest to use the version from the PVP file rather than the hard-coded `0.2.0-preview.20419.2`.

Use our Microsoft.Diagnostics.NETCore.Client, not prebuilt

---

Directory.Build.props
eng/Version.Details.xml
patches/roslyn-analyzers/0001-WIP-for-source-build.patch
patches/roslyn-analyzers/0002-Update-to-netstandard2.0.patch
patches/roslyn-analyzers/0003-Update-Microsoft.CodeAnalysis-packages.patch
patches/roslyn-analyzers/0004-Fix-version-for-Microsoft.CodeAnalysis.CSharp.CodeSt.patch
repos/roslyn-analyzers.proj
repos/sdk.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

This repo doesn't build out of the box on Linux, so I have added various build scripts and hacks to get that working.

Add dotnet/roslyn-analyzers repo

---

patches/vstest/0006-build-for-.NET-5.patch

By targetting .NET 5 instead of .NET Core 2.1 an apphost is included by default.
This updates the patch to not include the apphost.
Fixes https://github.com/dotnet/source-build/issues/1874
cc @omajid @dagood

vstest: don't include an apphost for vstest.console

---

build.proj
eng/SourceBuild.Tarball.targets
eng/Versions.props
patches/arcade/0015-Override-Microsoft.CodeAnalysis.CSharp-pkg-deps.patch
tools-local/prebuilt-baseline-offline.xml

Instead of downloading previously-source-built packages (prev-sb) from some N-1 build, use the tar.gz that the Production build built. This simulates a bootstrapping flow.
For https://github.com/dotnet/source-build/issues/1880

For 5.0.0, use bootstrapping in CI, not N-1

---

Directory.Build.props
repos/runtime.common.props

Recent discussion on https://github.com/dotnet/coreclr/pull/26082 suggests this should be working.

Re-enable system libunwind support

---

patches/sdk/00015-Lift-dotnet-runtime-dependencies-for-source-build.patch

For https://github.com/dotnet/source-build/issues/1896
This doesn't directly remove any prebuilts, but I expect it to allow us to add more SBRP packages without interfering with the SDK build.
A diff of annotated offline build usages seems to confirm this is doing what we want it to: https://gist.github.com/dagood/02e720f836a47b722a3f1e4f01f618d9

Lift dotnet/runtime dependencies in dotnet/sdk to use 5.0.0 packages in toolset

---

patches/runtime/0029-Fix-issue-44646-ILAsm-incorrectly-handles-method-.cu.patch

Patch is from https://github.com/dotnet/runtime/pull/44850
Fixes issue https://github.com/dotnet/runtime/issues/44646

Add patch for runtime ilasm generation fix

---

patches/roslyn-analyzers/0005-Disable-code-analyzers-when-building-from-source.patch
tools-local/prebuilt-baseline-offline.xml

For https://github.com/dotnet/source-build/issues/1893. (More details in patch.)

Patch roslyn-analyzers: remove analyzer prebuilts

---

eng/Version.Details.xml
eng/Versions.props
patches/humanizer/0001-Fix-building-in-a-source-build-context.patch
repos/aspnetcore.proj
repos/humanizer.proj
repos/roslyn.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

This is https://github.com/Humanizr/Humanizer (different from https://github.com/Humanizer/Humanizer !)
Humanizer shows up as a dependency of ASP.NET Core and roslyn-analyzers. This tries to fix that. Supposedly it also ships with the SDK.
Fixes: #1767

Add Humanizer.Core

---

patches/runtime/0001-Use-substitute-SHA-1-implementation-in-wasm-44982.patch

Port https://github.com/dotnet/runtime/pull/44982 from dotnet/runtime `master` to 5.0.0 GA as a source-build patch. (Applies cleanly.)
For https://github.com/dotnet/runtime/issues/44884.

runtime: Use substitute SHA-1 impl in wasm

---

patches/roslyn-analyzers/0006-Disable-AppHost.patch

See https://github.com/dotnet/source-build/issues/1905 for more information.
Upstream PR: https://github.com/dotnet/roslyn-analyzers/pull/4451

Remove Microsoft.NETCore.App.Host prebuilts from roslyn-analyzers

---

patches/fsharp/0006-Use-net5.0-TFM-to-avoid-3.1-apphost-prebuilt.patch
repos/fsharp.proj

`fsc` and `fsi` apphosts end up in the SDK, so I think they need to be `net5.0`.
`fslex`, `fsyacc`, and `AssemblyCheck` seem to be build-time tooling, so removing apphost generation might be an option. But we might as well move all these projects to `net5.0` consistently if possible.
For https://github.com/dotnet/source-build/issues/1905.
---
Adds dependency on `System.Configuration.ConfigurationManager` because it seems necessary now in my local build. I assume this is because of `net5.0`, but I'm not sure.
---
Also fixes a missing repo dependency that `fsharp` has on `msbuild`. It needs the new APIs available in new `msbuild` packages. This was preventing `/p:RootRepo=fsharp` from working:
```
.../src/fsharp/LegacyMSBuildReferenceResolver.fs(88,59): error FS0039: The type …
```

fsharp: Use net5.0 to avoid 3.1 apphost prebuilt

---

repos/Directory.Build.targets

Using a regex match with a full path results can result in the regex matching parent directories of the source directory. If the code is being compiled in a subdirectory with a full path that includes `net5.0`
(such as `dotnet5.0`), multiple loggers can match. Multiple loggers matching will produce an invalid msbuild command, failing the build.
To reproduce:
mkdir dotnet5.0
cd dotnet5.0
git clone https://github.com/dotnet/source-build
cd source-build
git checkout master
./build.sh
In my case, sourcelink fails to build with this error message:
MSBUILD : error MSB1008: Only one project can be specified.
Switch: /home/omajid/dotnet5.0/source-build/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/net472/Microsoft.DotNet.Arcade.Sdk.dll
Fixes: #1914

Fix matching logger path against parent directories

---

Documentation/README.md
Documentation/packaging-installation.md

This is a port of https://github.com/dotnet/source-build/pull/1653 to `master`.

Add documentation for packaging source-build (#1653)

---

smoke-test.sh

This helps us make sure that `dotnet new blazorwasm` and `dotnet new blazorserver` continue to work with source-build.
Fixes: #1724

Add smoke tests for blazor

---

eng/Version.Details.xml
eng/Versions.props

This PR updates to `.3` in parallel to `.2` (https://github.com/dotnet/source-build/pull/1924) in case one has issues and the other doesn't.
With this PR, all prebuilts should be gone except the targeting packs blocked by https://github.com/dotnet/runtime/issues/45183.

Update SBRP to 1.0.0-beta.20575.3

---

scripts/fetch-microsoft-sdk.sh

The script internally uses dotnet-install. The output of dotnet-install has changed: it now prints multiple urls and only one of them is the one we want.
> dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
> dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
> dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
> dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.
>
> dotnet-install: Payload URLs:
> dotnet-install: Primary named payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.110/dotnet-sdk-3.1.110-linux-x64.tar.gz …

[release/3.1] Fix fetch-microsoft-sdk script

---

Documentation/README.md

Document flags for building against system libraries

---

patches/runtime/0003-Add-source-build-specific-build-script.patch

Recreate the patch adding the dotnet/runtime `build-source-build.sh`: it wasn't adding the last line. This ends up overwriting the coreclr binlog in the portable build.
Fixes https://github.com/dotnet/source-build/issues/1943.

Fix coreclr binlog: corrupted patch

---

patches/runtime/0033-Build-net4-in-source-build.patch

Follow up on https://github.com/dotnet/source-build/pull/1928#discussion_r541174488. I tried to include context and guidance for what to do if this patch conflicts.

Improve "Build net4* in source-build" patch doc

---

smoke-test.sh

.NET Core 2.1 and 3.1 use separate strings of text to indicate that the application is running. Both include this text, though:
Application started. Press Ctrl+C to shut down.
Update the timeout detection logic to be more flexible and catch this line of text anywhere in the output, not just in the last line.
This brings the timeout for some of these test runs down from 30 seconds to 2 or 3 seconds.
Fixes: #1655

[release/3.1] Fix smoke test timeout detection to work again

---

NuGet.config
repos/Directory.Build.targets
repos/aspnetcore.proj
smoke-test.sh
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/ReplaceFeedsInNuGetConfig.cs

MyGet feeds have been deprecated and replaced with new feeds. 
This PR updates source-build infrastructure in cases where MyGet feeds were used and adds a task to update repo's NuGet.Config file(s) to replace feeds before building.
See #1971

[master] Replace legacy MyGet feeds

---

NuGet.config
global.json
repos/Directory.Build.targets
repos/aspnetcore.proj
repos/msbuild.proj
repos/websdk.proj
smoke-test.sh
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/ReplaceFeedsInNuGetConfig.cs

MyGet feeds have been deprecated and replaced with new feeds.
This PR updates source-build infrastructure in cases where MyGet feeds were used and adds a task to update repo's NuGet.Config file(s) to replace feeds before building.
See #1971

[release/3.1] Replace legacy MyGet feeds

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
Documentation/servicing/make-commit-available.md

Brief doc to describe this process. Make it easy to find by putting it in the checklist.
This is a way to mitigate the effect release tagging unreliability has on our releases (lag): https://github.com/dotnet/arcade/issues/5686.

[release/3.1] (Checklist) Document how to make a commit available

---

.vsts.pipelines/builds/matrix.yml
repos/Directory.Build.targets
repos/runtime.proj

Enable the currently-commented out CI setup for macOS.
Fix the find command used for logger:
- Always specify path: the macOS version of find needs that or a -path argument to work.
- The regex engines differ between GNU find and macOS find. The `\|` part is parsed differently by both of them. Use a simpler regex that they can both support.
Use `TargetOverrideRid` (`osx-x64`) instead of `TargetRid` (`osx.10.13-x64`) to determine the RID of the runtime tarball.
Fixes: #1819

Re-enable macOS CI

---

Documentation/planning/arcade-powered-source-build/onboarding/local-onboarding.md

A few small improvements that help link things together and make sure a binlog exists that someone can show us if their outer build goes wrong.
* Add links to docs that live in dotnet/arcade.
* Include binlogs in default command.
/cc @dseefeld @crummel

Add more info for onboarding process: link to docs living in arcade, include -bl in example command

---

README.md

I just forked `release/5.0` and I'm about to merge the first arcade-powered source-build change into `master`, removing all but a few repos. Update the readme to point new arrivals at the release branches.
This can probably be polished up some, but I want to get the pointers in first so ArPow can keep moving.

Update readme for 6.0 / arcade-powered source-build: point to release branches for SDK build

---

Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md

Updates the onboarding doc to match https://github.com/dotnet/arcade/pull/6790.
/cc @dseefeld @crummel

[master] Update ArPow onboarding doc for simplification

---

README.md

I mentioned in my earlier PR for the readme that I think it needs some more polish. Here I'm trying to put the release branches as early as possible and update the build commands to match the new state.
I removed the link to `Documentation/` because it details the full .NET SDK build that no longer happens in `master`. I think we should probably only keep the old docs in `release/5.0` because it seems like it would be too confusing to have to put intros about which branch each doc actually applies to. Once ArPow isdone, end-to-end-style docs should go to either dotnet/installer or dotnet/arcade.
It would be nice to make a new repo rather than use dotnet/source-build for this new purpose. It just seems too easy to argue that reuse makes sense since there is a relatively simple cutoff …

[master] Update README: more specific branch and plan info

---

eng/Version.Details.xml

The `<SourceBuild RepoName="arcade" ManagedOnly="true" />` element makes it so we get Arcade from the intermediate nupkg, reducing prebuilts:
```diff
<AnnotatedUsages>
-  <AnnotatedUsage Id="Microsoft.DotNet.Arcade.Sdk" Version="6.0.0-beta.21101.2" />
-  <AnnotatedUsage Id="Microsoft.DotNet.SourceBuild.Tasks" Version="6.0.0-beta.21101.2" File="src/artifacts/toolset/Common/project.assets.json" IsDirectDependency="true" IsAutoReferenced="true" Project="src/" />
<AnnotatedUsage Id="Microsoft.NETCore.Platforms" Version="1.0.1" File="src/src/newtonsoft-json901/Src/Newtonsoft.Json/obj/project.assets.json" Project="src/" />
<AnnotatedUsage Id="Microsoft.NETCore.Targets" Version="1.0.1" File="src/src/newtonsoft-json901/Src/Newtonsoft.Json/obj/project.assets.json" Project="src/" />
+ …
```

[master] Fix dependency on dotnet/arcade: use ArPow intermediate nupkg

---

Documentation/planning/arcade-powered-source-build/onboarding/local-onboarding.md

Add a quick overview of the initial setup and specify where the binlogs are. Should help out with the first steps if we get more people working from this doc in the future.

[master] Clarify ArPow initial setup requirements, binlog

---

eng/Publishing.props

This file with this content is required for Arcade publishing: https://github.com/dotnet/arcade/blob/0a67fb1cd008b0d30577f53d1633ed00db8bc1e6/Documentation/CorePackages/Publishing.md#how-to-upgrade-from-v2-to-v3
Otherwise, the inner publish job gets an error like this:
```
Creating a task to publish assets from D:\a\1\a\AssetManifests\Unix-AnyCPU.xml
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21101.7\tools\SdkTasks\PublishArtifactsInManifest.proj(103,5): error : The property TargetFeedConfig is required but doesn't have a value set.
##[error].packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21101.7\tools\SdkTasks\PublishArtifactsInManifest.proj(103,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) The property TargetFeedConfig is required but doesn't have a value set. …
```

[master] Add eng/Publishing.props to fix publishing

---

Documentation/planning/arcade-powered-source-build/implementation-plan.md

We lost @tmat's symreader champ listing in a remove/add shuffle: https://github.com/dotnet/source-build/issues/492 https://github.com/dotnet/source-build/issues/1812. Putting it back.
@tmat, let us know if you think it should be someone else now.
(I'm not aware of any reason it should change, but it has been a while. 😄)

[master] Re-add symreader source-build champ

---

Documentation/planning/arcade-powered-source-build/README.md
Documentation/planning/arcade-powered-source-build/intermediate-nupkg.md
Documentation/planning/arcade-powered-source-build/onboarding/local-onboarding.md

I started writing out what I was considering in https://github.com/dotnet/source-build/issues/2034, but I wrote enough that it fits better in the docs. Also, line review comments are always nice, rather than just one issue thread.
So far I'd only expect these to be needed for dotnet/runtime -> dotnet/aspnetcore -> dotnet/installer, perhaps dotnet/sdk -> dotnet/installer. (Also dotnet/runtime -> repos that need platform extensions libraries.)
/cc @MichaelSimons @omajid

ArPow: Add plan for supplemental intermediate nupkgs

---

README.md

The original `[Arcade-powered source-build](Documentation\planning\arcade-powered-source-build)` link produces a 405 because it gets translated to `https://github.com/dotnet/source-build/blob/master/Documentation%5Cplanning%5Carcade-powered-source-build` in GitHub.   Other tooling handles the back slashes just fine like VsCode.

Fix broken Arcade Powered Source-build link

---

.vsts.pipelines/builds/ci.yml

Add exclude paths to the build triggers so that CI/PR validation does not get run for documentation only changes.   Every time the ArPow implementation status is updated CI is currently running.

Add misc exclude build triggers

---

patches/runtime/0030-Add-TRUE-and-FALSE-definitions.patch

Local OSX doesn't repro, using this to figure out the issue.

[release/5.0] Add missing TRUE and FALSE definitions for OSX

---

.vsts.pipelines/stages/prepare-artifacts.yml

PrepareArtifacts downloads all artifacts from a given build job.  This is causing the host to run out of space.  Add an itemPattern to just download Private.SourceBuilt.Artifacts.

Download single artifact in PrepareArtifacts

---

smoke-test.sh

This probably should be reviewed commit by commit. The first commit is a cleanup fixing some warnings pointed out by shellcheck. The second commit is the test.
This assumes all the xml docs are only present in the targeting packs, and not anywhere else.
I am not sure if the ignore list is correct: do all the packages listed look okay?
Fixes: #2127

Add a test to verify xml/intellisense docs are present

---

smoke-test.sh

The argument isn't read before we start using the value of targetRid, sodefer using targetRid until after the argument has been read.
Fixes: #2081

[release/5.0] Make `./smoke-test.sh --targetRid $RID` work

---

build-source-tarball.sh

Running
./build-source-tarball.sh dotnet-v3.1.114-SDK-original
Leads to source-build trying to use
source-build/packages/restored/microsoft.dotnet.arcade.sdk/1.0.0-beta.20113.5/tools/dotnet-v3.1.114-SDK-original
instead of a top-level dotnet-v3.1.114-SDK-original directory.
Fix that.
Fixes: #2130

[release/3.1] Fix use of a simple directory name with build-source-tarball.sh

---

Documentation/README.md
Documentation/add-new-rid.md

Anyone else adding their Linux distribution's RID to source-build might find this useful.
I am trying to get this out of my head and into a shape where others can make use of this.
See: #2095

Add a doc describing how to add new RIDs to source-build

---

smoke-test.sh

Running worker application locally helped catch aspnet/common -> dotnet/extensions move. So lets add it to the smoke-tests as well.

[release/5.0] Add webapp and worker to smoke-tests

---

eng/Version.Details.xml
patches/newtonsoft-json/0001-Updated-AssemblyVersion-FileVersion-Version-Prefix-a.patch
patches/newtonsoft-json/0002-removed-ruleset-and-dependency-on-a-couple-packages.patch
patches/newtonsoft-json901/0001-Run-dotnet-migrate-to-generate-Newtonsoft.Json.Dotne.patch
patches/newtonsoft-json901/0002-Fixup-result-of-migration.patch
patches/newtonsoft-json901/0003-Use-correct-version-number.patch

https://github.com/dotnet/source-build/issues/2185
Currently, .NET 5.0 builds Newtonsoft.Json from a personal repo: https://github.com/adaggarwal/Newtonsoft.Json
This PR adds patches for the changes on that personal repo and builds from the official Newtonsoft.Json repo instead (https://github.com/JamesNK/Newtonsoft.Json), for both Newtonsoft.Json 9.0.1 and 12.0.2.

[release/5.0] Remove dependency on personal repo for Newtonsoft.Json 9.0.1 and 12.0.2

---

eng/Version.Details.xml
patches/newtonsoft-json/0001-Updated-AssemblyVersion-FileVersion-Version-Prefix-a.patch
patches/newtonsoft-json/0002-removed-ruleset-and-dependency-on-a-couple-packages.patch
patches/newtonsoft-json901/0001-Run-dotnet-migrate-to-generate-Newtonsoft.Json.Dotne.patch
patches/newtonsoft-json901/0002-Fixup-result-of-migration.patch
patches/newtonsoft-json901/0003-Use-correct-version-number.patch

Second half of https://github.com/dotnet/source-build/issues/2185, changes are pretty much the same as PR https://github.com/dotnet/source-build/pull/2366
Currently, .NET 3.1 builds Newtonsoft.Json from a personal repo: https://github.com/adaggarwal/Newtonsoft.Json
This PR adds patches for the changes on that personal repo, and points source-build to the official Newtonsoft.Json repo instead (https://github.com/JamesNK/Newtonsoft.Json) for both Newtonsoft.Json 9.0.1 and 12.0.2.

[release/3.1] Remove dependency on personal repo for Newtonsoft.Json 9.0.1 and 12.0.2

---

NuGet.config

The local view is all packages, and this confuses the nuget security analysis task.

[release/5.0 Remove view from dotnet-public

---

build.proj
smoke-test.sh
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/ParseDotNetVersions.cs

This makes it easier to visually confirm what was built:
Build Info:
SDK Version: 5.0.202
ASP.NET Core Version: 5.0.5
Runtime Version: 5.0.5
And also stores these values in named version files for later use.
The build output on the console looks like this:
```
Build Info:
SDK Version: 5.0.202
ASP.NET Core Version: 5.0.5
Runtime Version: 5.0.5
Build succeeded.
/home/omajid/devel/dotnet/source-build/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/ProjectLayout.props(8,3): warning MSB4011: "/home/omajid/devel/dotnet/source-build/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/RepoLayout.props" cannot be imported again. It was already imported at "/home/omajid/devel/dotnet/source-build/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426. …
```

[release/5.0] Print and store versions at end of every build

---

Documentation/planning/arcade-powered-source-build/onboarding/local-onboarding.md

The generated (arpow) source-tarball is often built in a context where it's under a subdirectory of an unrelated git repository. In such a situation, `git apply` will try and apply patches to the main git repository instead of the extracted source-tarball contents. That fails (silently), so the patches never get applied. Building that source-tarball eventually fails because of those missing patches.
Use --work-tree to tell git to apply patches to the tarball directory and not to whatever git repo the tarball directory happens to be under.
Fixes: https://github.com/dotnet/source-build/issues/2445

Use --work-tree with git apply in onboarding docs

---

.vsts.pipelines/builds/ci-internal.yml
.vsts.pipelines/builds/matrix.yml

Part of https://github.com/dotnet/core-eng/issues/14276
Internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1366458&view=results

Switch to servicing 1ES Pools in release/2.1

---

.gitmodules
patches/MSBuildLocator/0001-Eliminate-prebuilts.patch
repos/MSBuildLocator.proj

Fixes https://github.com/dotnet/source-build/issues/2510
Adding MSBuildLocator in this means is much lower cost than having the MSBuildLocator repo support source-build natively.  Given the low churn in the repo, I think this is the most reasonable solution for .NET 6.0.

Add MSBuildLocator to source-build

---

README.md

See https://github.com/dotnet/source-build/issues/2602 for more information.

Add instructions for building dotnet 6.0 from source

---

.vsts.pipelines/builds/ci.yml

Backport of https://github.com/dotnet/source-build/pull/2720
For .NET 6.0 and 7.0, source-build is focused on Linux, so our CI should reflect that.

[release/6.0] Remove macOS CI leg

---

.vsts.pipelines/builds/ci.yml

For .NET 6.0 and 7.0, source-build is focused on Linux, so our CI should reflect that.

[main] Remove macOS CI leg

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md

Motivation behind this is to enhance the new issue experience.  Direct issues/questions/discussions to the correct places in order to get quicker responses.
Related to https://github.com/dotnet/source-build/issues/2625

Add new issue template

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-local.yml
.vsts.pipelines/steps/run-bootstrap.yml
repos/Directory.Build.targets
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UsageReport/ValidateUsageAgainstBaseline.cs

* continue the build with a warning when there are new prebuilts
* append job attempt number to log artifacts so we keep artifacts from multiple attempts
Includes changes from https://github.com/dotnet/source-build/pull/2742 and the fix for https://github.com/dotnet/source-build/issues/2771

[release/5.0] CI improvements

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-linux_bootstrap.yml
.vsts.pipelines/jobs/ci-local.yml
.vsts.pipelines/steps/run-bootstrap.yml

Fixes #2771 by only appending numbers to logs artifacts. We very rarely have an issue where a build doesn't succeed but it still uploads a tarball. We should still be able to get logs for multiple attempts of things like smoke tests.

[release/3.1] Don't append attempt numbers to tarball artifacts in CI

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md

Poison check is now automated with https://github.com/dotnet/source-build/issues/2652 therefore the manual step is no longer needed in the release checklist.

Remove manual poison check in release checklist

---

eng/source-build-release-announcement.md
eng/source-build-release.yml

Moving https://github.com/dotnet/installer/pull/13498 to here.
fixes https://github.com/dotnet/source-build/issues/2776
This is the baseline for the source-build release pipeline that will automate our release day tasks for 6.0-onwards. The pipeline will always live in `main` and (when we have multiple post-6.0 releases) we will trigger it once for each release with the corresponding inputs.
Basic flow of the pipeline:
Inputs: SDK Version, Optional tag override
1. Detect tag from SDK version, or use the optional tag override. For example, if the SDK version `6.0.103` is provided, we will try to find the release tag `v6.0.103` since that is the current naming scheme. The optional tag override is for when we need to make a source-build specific tag, like …

[main] Introduce Source-Build release pipeline

---

eng/source-build-release.yml
eng/submit-source-build-release-pr.sh

Fixes https://github.com/dotnet/source-build/issues/2836
- Fix an incorrectly referenced variable in SetTag task
- Set git username and email for the source-build update commit
- Adjust formatting of commands that edit files so that Versions.props isn't accidentally deleted. I'm not sure what formatting mistake led to the output being empty, so I reverted to the last known working version from when I tested it (and I re-tested it of course).

[main] Fix several release pipeline PR issues

---

eng/submit-source-build-release-pr.sh

Should fix https://github.com/dotnet/source-build/issues/2896. I tested the in-place editing syntax locally and it works, but I did not run a full release pipeline in private repos and such.

Use sed in-place to edit Versions.props in release PR

---

repos/Directory.Build.targets

Port of https://github.com/dotnet/source-build-externals/pull/27 to release/6.0 - sorry, misunderstood how source-build-externals was working these days.
In the installer tarball build, we want to remove the `objects` directories from the .gitdirs in order to save space and allow the tarball to be checked into a Git repo itself.  This causes a problem in the specific configuration of a submodule with a redirected .gitdir where the `objects` directory has been deleted - Git will error out attempting to apply patches from that current directory.  This introduces a workaround by setting GIT_DIR to /dev/null, so Git will skip .gitdir discovery and instead treat the submodule directory like any other non-source-controlled directory.  This is acceptable because we just need the patches to be …

Force skipping .gitdir discovery when patching submodules.

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md

The PR attempts to clarify the steps needed to gather the smoke-test prereqs.

Add precise release checklist steps for smoke-test prereqs

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
Documentation/servicing/common-prebuilt-issues.md
Documentation/servicing/update-3.1.md

Update our 3.1 servicing checklist with things we learned from June's servicing.  Also start centralizing knowledge about common prebuilt patterns.

Update documentation with notes from June servicing.

---

.vsts.pipelines/builds/ci.yml
eng/common/templates/job/source-build.yml
eng/common/templates/job/source-index-stage1.yml

This change is required to continue building PRs in the dotnet public repo.  The agents and images used in the new project / organization are identical and build regressions are not expected.
For questions / concerns, please stop by the .NET Core Engineering Services [First Responders Teams Channel](https://teams.microsoft.com/l/channel/19%3aafba3d1545dd45d7b79f34c1821f6055%40thread.skype/First%2520Responders?groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).

Update public pool names

---

.vsts.pipelines/builds/matrix.yml

See https://github.com/dotnet/arcade/issues/10632 for more context. The machines are being decommissioned and there isn't much value in spending time and effort keeping these legs running, since we already build and test on CentOS 7 and 8.

[release/3.1] Disable RHEL CI

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
eng/source-build-pre-release.yml
eng/templates/get-build-info.yml
eng/templates/installer-pipeline-variables.yml

Fixes https://github.com/dotnet/source-build/issues/2710. Part of https://github.com/dotnet/source-build/issues/3065
This is a new pipeline that:
1. Reads installer build information from our internal release (non-source-build) pipelines
2. Uploads the dotnet source tarball to azure storage

[main] Add source-build-pre-release pipeline yaml

---

eng/source-build-pre-release.yml
eng/update-vmr.sh

Fixes https://github.com/dotnet/source-build/issues/3064

[main] Automatically create new security-partners-dotnet branches with tarball contents in pre-release pipeline

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
test/GatherPackages.csproj

This adds the GatherPackages.csproj used to get the smoke-test prereqs - I thought having this centralized and working for all versions was worthwhile.  I will add instructions for use to the checklist when I make that PR.

Add GatherPackages to grab smoke-test prereqs.

---

eng/source-build-pre-release-8.0.yml
eng/source-build-release-mirror.yml

There were a couple of minor things such as it could only push to an already existing branch.
I was able to mirror a dev branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=2112291&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=bf6cf4cf-6432-59cf-d384-6b3bcf32ede2
https://github.com/dotnet/source-build/issues/3194

Make the SB mirroring pipeline work for 8.0 preview 1

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
eng/get-build-info.sh
eng/source-build-release-announcement.md
eng/source-build-release-official.yml
eng/templates/stages/pre-release.yml
eng/templates/stages/release.yml
eng/templates/steps/initialize-release-info.yml

There are many improvements in this PR to the SB release pipeline:
- Release tag now comes from staging pipeline information so preview releases work without a custom tag (https://github.com/dotnet/source-build/issues/3269)
- It is possible to specify a human readable name (e.g. ".NET 8 Preview 1") that is used during the release
- Used in announcement title
- Used in release title
- Added automation for creation of tag+release in the dotnet/dotnet repo (https://github.com/dotnet/source-build/issues/3271)
- We use `pack-sources.sh` to append sources to the release (temporary fix for https://github.com/dotnet/source-build/issues/3265)
- Release can be created as a draft - the tag is then only published once we publish the draft
- Example release: …

Automate creation of GitHub tag & release 

---

eng/get-build-info.sh
eng/push-tarball.sh
eng/source-build-release-official.yml
eng/templates/stages/mirror.yml
eng/templates/stages/release.yml
eng/templates/steps/initialize-release-info.yml

This version of the pipeline was used to pre-release and mirror 6.0/7.0 March 2023 releases.
- Improve how dry-run behaves when triggered during various stages of actual release in progress
- Solidify re-runs of non-dry-runs when previous attempts had to be cancelled
- E.g., more defensive approach when doing the DSP mirroring
- Fixes how we handle branches/tags for 6.0/7.0
- Do not push branches to DSP anymore, just tags
- Deduce the release month by adding 14 days instead of 1 month

Improve / fix the SB release pipeline for 6.0/7.0 flows

---

eng/source-build-release-official.yml
eng/templates/stages/mirror.yml

During the relese automation, push packages from current release to feed accessible to dotnet-security-partners.

Mirror packages to dotnet-security-partners

---

eng/templates/stages/release.yml

I have updated the CI leg names in https://github.com/dotnet/installer/pull/15603.
There is still an open question of how we can make sure leg names are shared across these multiple pipelines.
I think that after .NET 8 is released, or whenever we are prebuilt-clean and will likely not require a re-bootstrap, we should get artifacts from the `CentOSStream8_Offline_PreviousSourceBuiltSdk` leg instead of the `CentOSStream8_Offline_MsftSdk` leg. This would prevent us from using any Microsoft-built binaries at any point past the initial bootstrap during the .NET 8.0 servicing.

[main] Use new CI leg name

---

eng/templates/stages/mirror.yml

This will allow re-runs of the pipeline
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2135894&view=logs&j=b6422d7d-1f12-5a27-5bca-0651b2848f2b&t=32705529-1086-50d7-1e7e-88b31414415c&l=35

Skip mirroring when the tag already exists

---

eng/push-tarball.sh

Fixes https://github.com/dotnet/source-build/issues/3069.
Release pipieline dry run is at https://dnceng.visualstudio.com/internal/_build/results?buildId=2138107&view=results.

Add call to create PR in AzDo servicing.

---

eng/source-build-release-official.yml
eng/templates/stages/mirror.yml

One final adjustment to match what was discussed in https://github.com/dotnet/source-build/issues/3317#issuecomment-1472501742

Use runtime version as the release tag for 6.0/7.0

---

eng/templates/stages/mirror.yml

Resolves #3381
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2164071&view=logs&j=b6422d7d-1f12-5a27-5bca-0651b2848f2b&t=3e07d252-5687-5ff1-9e2c-f75b5de04ae8

Use the `Build.Ubuntu.2004.Amd64` pool for package mirroring

---

eng/submit-source-build-release-pr.sh

This didn't happen 100% of the time so I guess we didn't notice earlier. Probably a race condition in how `jq` reads and writes to the same file at the same time
Fixes #3378

Prevent nuking of `global.json` in release PRs

---

eng/create-announcement-draft.sh
eng/source-build-release-announcement.md

Resolves #3382
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2166629&view=logs&j=3a04dffd-22cf-5707-fa41-9bd4708cc1db&t=b33c9200-20e6-56d2-908d-d0d0eca38f08&l=14

Omit build number in announcement title of preview releases

---

eng/create-announcement-draft.sh
eng/source-build-release-notes.md
eng/templates/stages/release.yml

https://github.com/dotnet/source-build/issues/3366
Example release: https://github.com/dotnet/dotnet/releases/tag/untagged-563947d5583e5a29f43d
Example `release.json`:
```json
{
"release": "8.0.100-preview.3",
"channel": "8.0",
"tag": "v8.0.100-preview.3.23178.7",
"sdkVersion": "8.0.100-preview.3.23178.7",
"runtimeVersion": "8.0.0-preview.3.23174.8",
"sourceRepository": "https://github.com/dotnet/dotnet",
"sourceVersion": "6d6f38c2d65c50dfc31dcdadfef1ba24ed4efc45"
}
```
The linked instructions are added here: https://github.com/dotnet/installer/pull/16184

Add release manifest and instructions to dotnet/dotnet releases

---

eng/push-tarball.sh
eng/templates/stages/pre-release.yml

It is conceivable that the PR created by Update security-partners-dotnet has already been merged if Pre-release stage is executed more than once. 
Issue Link: https://github.com/dotnet/source-build/issues/3353
Pipeline Link: https://dev.azure.com/dnceng/internal/_build/results?buildId=2174527&view=logs&j=3a04dffd-22cf-5707-fa41-9bd4708cc1db&t=43d9a424-b64c-5d30-c3bd-0fca912bd01a

Skipping PR creation in the absence of any commits

---

eng/submit-source-build-release-pr.sh
eng/templates/stages/release.yml

https://github.com/dotnet/source-build/issues/3344
https://github.com/dotnet/source-build/issues/3385
In .Net 8.0.*, the content of the relevant element has been obtained, and the very last part of the URL has been replaced using regex. But in .Net 7.0.* and 6.0.* the entire content has been set to the SDK version.
In DryRun mode, the submit-sorce-build-release-pr script has been called.
In the final phase, right before raising the PR, the creation of the pull request has been disabled. 
The contents of the VersionsProps file were compared and printed to ensure that the desired changes were implemented correctly. The results for each version are shown below.
Test for 8.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2184104&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t= …

Updating PrivateSourceBuilt elements in the Versions.props file correctly.

---

eng/templates/stages/release.yml

There were 35 draft releases published in the repo. I think we should skip on dry runs and if you want to test what the release in `dotnet/dotnet` looks like, you can run a dry run and set the setting to `draft`
Additionally, the GitHub page is buggy so it was hard to delete the draft releases

Do not publish draft VMR release on dry runs

---

eng/submit-announcement.sh
eng/submit-source-build-release-pr.sh
eng/templates/stages/release.yml

https://github.com/dotnet/source-build/issues/3450
Duplication has been avoided by determining whether or not an announcement with the identical title already exists. 
https://dev.azure.com/dnceng/internal/_build/results?buildId=2190080&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=a83d7a9e-2e19-5733-3923-52a07f576962
In addition, the code has been checked in the test repository.

Prevent duplicate announcement

---

eng/templates/stages/pre-release.yml
eng/templates/stages/release.yml
eng/templates/steps/upload-to-blob-storage.yml
eng/templates/variables/pipelines.yml

There's been some sort of change in behavior with Azure storage that causes the downloading of tarballs that were uploaded by the release pipeline to not have a `.gz` extension. They get downloaded just as a `.tar` extension. This is now true for even tarballs that were uploaded from previous releases that, at the time, were working but now get downloaded with the incorrect file extension.
I tracked this down to the content type that's set by default for these files. They have a content type of `application/x-tar`. In order to have the expected behavior, they need to have a content type of `application/x-gzip`.
To fix this, I've updated the command which uploads the files to explicitly set the content type to `application/x-gzip`.

Set content type for uploaded tarball

---

Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md

This updates the CI onboarding guidance with the following changes:
- Specify current unmanaged platform used by other `dotnet` repos, i.e. `runtime`
- Clarify the location for platform-related changes

Update unmanaged platform guidance

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
eng/combine-tarballs.sh
eng/templates/stages/mirror.yml
eng/templates/stages/pre-release.yml
eng/templates/steps/download-smoke-test-prereqs.yml
eng/templates/variables/msrc-storage-variables.yml

Updates the release pipeline to generate the smoke test prereqs tarball and upload it to blob storage for use by .NET security partners. This is implemented by combining the individual smoke test prereqs tarballs from an x64 and arm64 build leg of the source-build pipeline.
This does not implement logic to provide this tarball for public use. That's in the scope of https://github.com/dotnet/source-build/issues/3015.
Fixes https://github.com/dotnet/source-build/issues/3386

Upload smoke test prereqs tarball

---

eng/templates/stages/release.yml

A dry run of the release pipeline for 6.0 revealed a failure when attempting to upload the SB artifacts tarball in the release stage:
```
##[error]File /mnt/vss/_work/1/Private.SourceBuilt.Artifacts.6.0.121.tar.gz not found on disk. It might not have been downloaded. Exiting...'
```
This is due to the changes in https://github.com/dotnet/installer/pull/16855. The tarball has a new name that needs to be reflected in the release pipeline.

Update SB artifacts filename to include RID for 6.0/7.0

---

eng/templates/stages/release.yml

Resolves https://github.com/dotnet/source-build/issues/3637
Tag VMR commit of the build being released and push the said commit before creating a GitHub release.
Even if the commit is coming from the `internal` VMR, pushing the tag would just result in dangling commits at the time of release until the `internal` branch is merged back. Example of a tag with 2 commits from `internal` pushed via a tag - https://github.com/oleksandr-didyk/installer/releases/tag/test-mirror
GitHub CLI can use an existing tag for a release ([command docs](https://cli.github.com/manual/gh_release_create)). Added `--verify-tag` as a safe-guard to make sure the tag is re-used and the command does not create a new one accidentally. Example of a release from a tag mentioned above - …

Tag build commit before releasing

---

eng/templates/stages/release.yml

The script changes that were made in https://github.com/dotnet/source-build/pull/3638 didn't have enough indentation. This prevents the pipeline from being loaded in AzDO.
It fails with the error:
```
Encountered error(s) while parsing pipeline YAML: /eng/templates/stages/release.yml: (Line: 156, Col: 9, Idx: 5047) - (Line: 156, Col: 9, Idx: 5047): While scanning a simple key, could not find expected ':'.
```

Fix YAML formatting in release stage

---

Documentation/sourcebuild-in-repos/new-repo.md

Key updates include:
1. Use of new `-sb` build script option
2. Prebuilt baseline should not allow all prebuilts by default
3. Changes to prebuilt baseline requires source build team approval
4. Update CI guidance to use floating tags for the dotnet-buildtools/prereqs images
5. Consistent terminology use of source build instead of source-build.

Update new-repo guidance

---

eng/templates/stages/release.yml

Found during work on https://github.com/dotnet/arcade-services/issues/2956
In initial implementation I forgot about a case where both the tag and the release exist. Currently it will fail the pipeline, so added a warning for it instead (similar to what is in the internal pipeline as per the corresponding [PR](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/34985?path=/eng/pipeline/source-build-release/source-build-pr-net6.yml&discussionId=149407))
Test runs:
- dry run -> https://dev.azure.com/dnceng/internal/_build/results?buildId=2305971&view=results

fixup failure on existing release

---

eng/templates/stages/mirror.yml

When attempting to run the release pipeline for 8.0 GA, an error occurred when attempting to mirror the tag to the partners repo:
```
Tagging 40e7f014ff784457efffa58074549735e30772ae as v8.0.0
Tag v8.0.0 already exists, checking if it points to the same commit
Tag v8.0.0 already exists but does not point to a 40e7f014ff784457efffa58074549735e30772ae, aborting
```
This is because the logic which checks for an existing tag is not constrained enough:
https://github.com/dotnet/source-build/blob/198e13b4ad85563ffa2de1c79734501442257dde/eng/templates/stages/mirror.yml#L153
It simply greps on the tag name. But the repo already contains tags like `refs/tags/v8.0.0-preview.7.23375.6`. So it's matching on those and thinks the `v8.0.0` tag already exists when it does not.
I've updated the logic to …

Fix tag matching logic

---

eng/templates/stages/mirror.yml

Resolves issue found by https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullRequest/35064#1699280994
During porting the changes introduced by https://github.com/dotnet/source-build/pull/3716 to internal project discovered a small issue with the `tagGrepQuery` regex, specifically an un-escaped symbol.
Fix tested in internal project - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35064

fixup tagGrepQuery

---

eng/templates/stages/mirror.yml

Pointed out by https://github.com/dotnet/source-build/pull/3725#discussion_r1385018122
Caught by validation for https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35131
Fixup for `broken pipe` error caused by `grep -q` exiting on first match even if the first command is still outputting to the pipe.
Dry run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2311635&view=results

fixup grep broken pipe error

---

Documentation/leak-detection.md
Documentation/poison-report-format.md

Closes https://github.com/dotnet/source-build/issues/3732
Adds information related to adding detection of leaked reference assemblies.

Include SBRP attribute info in poison docs

---

eng/templates/stages/mirror.yml

Updates the leg name based on the change made here: https://github.com/dotnet/installer/pull/17696

Fix Debian Arm leg reference for 6.0

---

eng/templates/stages/mirror.yml

The `continueOnError` flag is included as part of https://github.com/dotnet/source-build/pull/3394 but that's not the behavior we want. We want the publishing to be skippable but if it does run, we want it to fail the build if there's an error.

Ensure error during package publishing fails the build

---

Documentation/package-dependency-flow.md

Is this documentation useful?  Is there something missing you would like to see added?  Please share your feedback.

Add package dependency flow documentation

---

Documentation/VMR-re-bootstrapping.md

This PR adds:
- Uploading of PSB artifacts archives
- Updating of Versions.props file

Update VMR re-bootstrapping guidance

---

Documentation/VMR-re-bootstrapping.md

Adds a note about using the SB lite pipeline to get the rebootstrapping artifacts.

Add note about source-build-lite pipeline

---

Documentation/VMR-re-bootstrapping.md

For .NET 9, SDK tarball and installers are produced by sdk pipeline.

Update guidance with reference to sdk pipeline

---

Documentation/VMR-re-bootstrapping.md

Related to https://github.com/dotnet/source-build/issues/4246
Updates the VMR re-bootstrapping document to include info about the new pipeline.

Update re-bootstrapping doc with re-bootstrap pipeline

---

Documentation/ci-platform-coverage-guidelines.md

Without testing on an old glibc version, it's possible we will have a release of .NET that doesn't actually work there. That could be an issue with the bootstrap artifacts, or with something else.
This came up in https://github.com/dotnet/source-build/issues/4399.

Update CI policy to cover testing on oldest glibc version

---

Documentation/patching-guidelines.md

Fixes https://github.com/dotnet/source-build/issues/4505

Update patching guidelines for installer->sdk merge and UB schedule

---

Documentation/ci-platform-coverage-guidelines.md

Updated the _Guidelines for Platforms Tested in CI_ per the changes made with https://github.com/dotnet/source-build/issues/4399.

Update SB's CI distro coverage guidelines

---

Documentation/VMR-re-bootstrapping.md
Documentation/bootstrapping-guidelines.md

Closes https://github.com/dotnet/source-build/issues/4511
This PR adds a note to the re-bootstrapping documentation warning users to not use the pipeline for testing. It also links to the documentation about how to do a stage 2 build. This documentation has also been updated to reflect recent build configurations.

Clarify use of rebootstrapping pipeline & update stage 2 build instructions

---

.github/workflows/markdownlint.yml
.markdownlint.json
CODE-OF-CONDUCT.md
Documentation/VMR-re-bootstrapping.md
Documentation/boostrap-new-os.md
Documentation/bootstrapping-guidelines.md
Documentation/ci-platform-coverage-guidelines.md
Documentation/eliminating-pre-builts.md
Documentation/leak-detection.md
Documentation/package-dependency-flow.md
Documentation/packaging-installation.md
Documentation/patching-guidelines.md
Documentation/planning/arcade-powered-source-build/README.md
Documentation/planning/arcade-powered-source-build/intermediate-nupkg.md
Documentation/planning/multi-sdk-band-support.md
Documentation/poison-report-format.md
Documentation/sourcebuild-in-repos/adding-features.md
Documentation/sourcebuild-in-repos/build-info.md
Documentation/sourcebuild-in-repos/new-dependencies.md
Documentation/sourcebuild-in-repos/new-repo.md
Documentation/sourcebuild-in-repos/update-dependencies.md
Documentation/system-requirements.md
README.md

This is in response to https://github.com/dotnet/source-build/pull/4539/files#r1705996684.  I originally hoped to re-enable the MD013 rule but discovered it applies to code blocks as well.  There are several places where this produces undesirable results therefore I am leaving the rule disabled but still re-formatted the MD files to limit the long lines.  I used the 'Rewrap' vscode extension to reformat the files.

Reformat MD files to limit line lengths to 80 characters

---

.github/linters/.check-markdown-links.json
.github/workflows/check-markdown-links.yml
Documentation/VMR-re-bootstrapping.md
Documentation/planning/arcade-powered-source-build/README.md
Documentation/planning/multi-sdk-band-support.md
Documentation/sourcebuild-in-repos/new-repo.md
Documentation/system-requirements.md

These changes include:
Add a GH action that validates links in all Markdown files. The action is the same one used in several dotnet repos already - core, monitor, etc.
Fix the numerous invalid links surfaced by the new link validator.

Add Check Markdown Link GH action

---

Documentation/ci-platform-coverage-guidelines.md

Related to https://github.com/dotnet/source-build/issues/4593#issuecomment-2332182331

Update the CI platform guidance to include update process

---

Documentation/eliminating-pre-builts.md
Documentation/sourcebuild-in-repos/new-dependencies.md
Documentation/sourcebuild-in-repos/new-repo.md
Documentation/sourcebuild-in-repos/update-dependencies.md

Related to #https://github.com/dotnet/source-build/issues/4645

Update source build GitHub team name

---

Documentation/planning/multi-sdk-band-support.md
Documentation/sourcebuild-in-repos/build-info.md
Documentation/sourcebuild-in-repos/update-dependencies.md
Documentation/system-requirements.md
README.md

Fixes https://github.com/dotnet/source-build/issues/4705.
Note:  There are a few remaining 6.0 references that are appropriate to leave as is (e.g. https://github.com/MichaelSimons/source-build/blob/9615023d4b99c46a62e20466100029084f70d74b/Documentation/poison-report-format.md#L8-L9)

Remove 6.0 references from documentation

---

Documentation/ci-platform-coverage-guidelines.md

Related to https://github.com/dotnet/source-build/issues/4819

Update platform doc to reflect removal of alpine n-1 build leg

---

.github/linters/.markdown-lint.yml
Documentation/how-to-stage2-build.md

Fixes https://github.com/dotnet/source-build/issues/4422

Add how to documentation for stage 2 builds

---

Documentation/ci-platform-coverage-guidelines.md

Closes https://github.com/dotnet/source-build/issues/5292
Will publish after I complete the full update in case I need to adjust steps along the way.

Document the Distro Upgrade Process
