README.md

This is to unblock people coming in.
/cc @crummel @dleeapho @richlander

Update build instructions temporarily

---

netci.groovy

FYI. @jaredpar.
Follow up to https://github.com/dotnet/dotnet-ci/commit/af4c59086c6ea9664c06273ae3aa2f1161802362

Updating the netci.groovy to no longer use InternalUtilities.

---

build.proj

I've been using this for quick iterative testing of patches without building everything.

Add target to only run patches for debugging.

---

arm-ci.sh
netci.groovy

- Add some docker debugging.
- Re-enable ARM PR builds.

Some work toward fixing ARM builds.

---

.gitattributes
dir.props
patches/cli-deps-satellites/0001-Allow-cli-deps-satellites-to-skip-signing-on-Windows.patch
patches/nuget-client/0004-Only-build-netstandard-and-netcoreapp-assets-on-NIX.patch

Merge master into dev/release/2.0

---

Documentation/README.md

@jaredpar @eerhardt 
These are the basic commands but please let me know if you want to see other things documented. 
skip ci

Update some basic commands in the documentation

---

Documentation/RepoApi.md

See #145, #146 and in the doc for justification
@dotnet/source-build-contrib

Add repo api doc

---

netci.groovy

Add CentOS to list of OS's in CI

---

Documentation/auto-dependency-flow/api.md

Documenting which properties haven't been implemented yet.
/cc @dotnet/source-build-contrib @jaredpar

Update dependency flow doc for not implemented

---

patches/cli/0003-Don-t-pull-down-stage-0-from-the-internet.patch
patches/cli/0014-Enable-CLI-to-build-on-Windows-during-source-build.-.patch
targets/fsharp.props

Correcting the shell extension and the PATH manipulation.
@dotnet/source-build-contrib

Fix F# build on Windows.

---

targets/cli.props

Fix Windows build - add -NoProfile to powershell script invocation in targets/cli.props

---

build.proj
dir.props
repos/application-insights.proj
repos/cli-deps-satellites.proj
repos/cli-migrate.proj
repos/clicommandlineparser.proj
repos/common.proj
repos/fsharp.proj
repos/javascriptservices.proj
repos/msbuild.proj
repos/netcorecli-fsc.proj
repos/newtonsoft-json.proj
repos/nuget-client.proj
repos/roslyn.proj
repos/sdk.proj
repos/symreader-portable.proj
repos/symreader.proj
repos/templating.proj
repos/xliff-tasks.proj

Remove root ApplyPatches and clean-up dotnetcommmand properties

---

repos/dir.targets

Only point at the repo log if it exists.

Update repo error message

---

.gitmodules

Switch back to using NuGet's NuGet.Client repo.

---

init-tools.sh

Add execute_with_retry() and display_error_message() to init-tools.sh.  Bringing other changes from core repos versions of init-tools.sh
Fixes dotnet/core-eng#1966

Add retry in init tools

---

README.md

Add build badges for master.

---

README.md

Add build badges to release/2.0.

---

scripts/bootstrap/buildbootstrapcli.sh

This adds a crossgen pass for cross platform runs.  
If crossgen fails, does a ildasm ilasm roundtrip to remove x64 crossgen
@janvorli PTAL

Add bootstrap crossgen support

---

README.md
netci.groovy

This depends on @dseefeld's changes which are not in yet - this may need to be updated after those go in.

Update CI for 2.1.

---

Documentation/2.1-update-process.md

Add document with process for updating source-build for 2.1

---

repos/known-good.proj
repos/symreader-portable.proj
repos/symreader.proj

These repos have repo toolset and build script fixes and should work now. Local tarball and offline tarball builds (with just these two repos included) seem good.

Add symreader and symreader-portable to known-good

---

NuGet.Config
patches/vstest/0001-Remove-build-for-net451-in-source-build.patch
patches/vstest/0002-Remove-unneccessary-projects-from-sln.patch
patches/vstest/0003-Update-build-script-to-only-includ-netcore-for-packa.patch
repos/known-good.proj
repos/vstest.proj

Add vstest to known good project.  Including some previously used patches until vstest source gets updated.

Add vstest to known good

---

.gitmodules
patches/cli-migrate/0001-Exclude-all-test-projects-from-source-build.patch
patches/cli-migrate/0002-Skip-_GenerateRepoDirectoriesAttribute-in-BfS.patch
patches/clicommandlineparser/0001-Exclude-additional-test-project-from-source-build.patch
patches/sdk/0001-Remove-log-option-from-defaults.patch
patches/sdk/0002-Change-to-2.1.101-SDK.patch
patches/sdk/0003-Exclude-all-test-projects-from-source-build.patch
repos/cli-migrate.proj
repos/clicommandlineparser.proj
repos/known-good.proj
repos/sdk.proj
repos/symreader-portable.proj
repos/symreader.proj

Uses patches against a dev branch in the main repos.
/cc @dleeapho @weshaggard

Add sdk, CliCommandLineParser, cli-migrate to known-good

---

dir.props

Default to portable builds on windows

---

repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
repos/sdk.proj

Updating the version info for the core repos and the sdk to sync with versions that were shipped in preview2.

Update version info for core repos and sdk

---

repos/cli.proj
repos/known-good.proj

There are a handful of repos that build in RC.  Un-commenting them from known-good.proj.

Adding more repos that build in RC

---

repos/roslyn.proj
repos/websdk.proj

Add roslyn, websdk auto-update: prodcon caught up

---

repos/cli.proj
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
smoke-testNuGet.Config

This gives us a first look at the aspnetcore experience in practice for 2.1-rtm source-build.

Use rtm aspnetcore packages

---

README.md

Update Readme for build changes.

---

repos/dir.props

Porting this from the RC branch.

Add ability to use stable versions for RTM.

---

repos/cli.proj

New prodcon build hasn't come out yet but this is the CLI hash that it will be (https://github.com/dotnet/cli/commit/32f29b6eb9fd4088625b1dea76000f0211c32305).

Update CLI for new prodcon build.

---

netci.groovy

Merge Netci.groovy to master from dev/release/2.1

---

repos/coreclr.proj

Fix core windows build

---

Documentation/boostrap-new-os.md

Something that i missed in https://github.com/dotnet/source-build/pull/377.

Fix typo 2.0 -> 2.1

---

Documentation/README.md

 Add documentation on how to produce a .NET Runtime and how to consume it

---

Documentation/README.md
repos/core-setup.proj

Bin place produced runtime by core-setup in bin folder

---

cross/x86/sources.list.trusty
cross/x86/sources.list.vivid
cross/x86/sources.list.wily
cross/x86/sources.list.xenial

Addes source.list for x86

---

netci.groovy

This is a port of https://github.com/dotnet/source-build/pull/659, the same change to master.
* Add more logs in the archive settings.
* Set log archiving to also happen on success.
* Add log archiving for tarball build subdirectories.
* Also suppress verbose smoke-test output as we have these logs archiving now.

[release/2.1] Add more logs in the archive settings.

---

netci.groovy

[release/2.1] Remove online tarball build from CI in favor of enforced offline build.

---

netci.groovy

[master] Remove online tarball build from CI in favor of enforced offline build.

---

netci.groovy

Some issue only repro with an only tarball build - e.g. PR #653.
This is a partial reversion of c23280994d79171fef45f4e0727e01d88cdd74f2 - I left the offline CentOS build leg in.

[master] Add online tarball builds back in.

---

.vsts.pipelines/phases/ci-linux.yml
netci.groovy
repos/dir.targets

https://github.com/dotnet/source-build/issues/762

[release/2.1.3] Warn on online baseline failure for offline legs

---

netci.groovy

Set up CI to use leak detection is the CentOS tarball and offline builds.  Getting this in before the actual leak detection stuff so we can be sure everything works all the way through.

Add leak detection to CentOS builds.

---

ProdConFeed.txt
dependencies.props
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
repos/sdk.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

This is the final 2.2.0-preview3 build being prepped for release. Baseline changes are only version changes.
Next steps: thorough submodule check (to avoid problem in https://github.com/dotnet/source-build/issues/748), then prebuilt audit.

[release/2.2] Update ProdCon, baselines to 20181014-01-2116274

---

ProdConFeed.txt
dependencies.props
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
repos/sdk.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Update to just-published https://github.com/dotnet/versions/tree/cae6079213809461b63e60ecd2b7b40e053d04fc/build-info/dotnet/product/cli/release/2.2.0.
Includes updates to CoreCLR, CoreFX, Core-Setup submodules.

[release/2.2] Update ProdCon to 20181110-02-2202235

---

build-source-tarball.sh
build.proj
dir.props
eng/Version.Details.xml
eng/Versions.props
tools-local/prebuilt-baseline-offline.xml

* Add reference-packages to dependencies
* Add target to download and untar reference-packages tarball
* Copy reference-packages to tarball

Add reference-packages dependency, download and untar to source-build

---

patches/core-setup/0003-Import-dependencies-props-after-eng-Versions-props.patch

Add patch to import dependencies.props after eng/Versions.props in core-setup

---

eng/Version.Details.xml
patches/nuget-client/0003-Add-roslyn-tools-restore-source-back-to-NuGet.Config.patch
repos/nuget-client.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

Update commit for nuget-client to get recent changes

---

patches/linker/0003-Don-t-add-sources-when-building-offline.patch
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/AddSourceToNuGetConfig.cs

UpdateNuGetConfig adds <clear/> if not present

---

build.proj
tools-local/init-build.proj

Add a target to just clone source.

Add Clone target to build

---

build-source-tarball.sh

Experimenting with a few different things to try and get the size of the tarball down.

Copy only the packages that we need the stage1 version of into the tarball

---

build-source-tarball.sh

Fixes https://github.com/dotnet/source-build/issues/1186

Remove System.Threading.Tasks.Extensions workaround

---

patches/aspnetcore/0005-Match-new-NuGet-MSBuild-version.patch
patches/aspnetcore/0008-Remove-prebuilts-for-source-build.patch

Update msbuild version to a reference-package version.
Add a patch based on work done in aspnetcore for preview 9.

Update msbuild version and add prebuilt reduction patch

---

patches/vstest/0003-Add-the-condition-for-Source-build-2144.patch

Add patch to fix building of datacollector project

---

patches/msbuild/0002-Add-Microsoft.Build.Localization-to-msbuild-for-sour.patch
repos/msbuild.proj

This adds building the Microsoft.Build.Localization package, which is showing as a prebuilt for toolset.

Build Microsoft.Build.Localization in msbuild repo

---

scripts/bootstrap/buildbootstrapcli.sh

Core-setup build produces different artifacts starting with .NET Core 3.0. Adjust the build script to handle .NET Core 2.x vs later versions differently.
If the bootstrapping is being done on a linux distribution, add "linux" and "linux-$ARCH" to the runtime graph too.
Also use 'set -u' in the bootstrap script to error out if there are undefined variables.
I was able to use this to "bootstrap" a source-built 3.0 Preview 6 SDK on Fedora 30/x64.

Enable bootstrapping .NET Core 3.0 builds

---

patches/arcade/0002-Do-not-build-.NET-Fx-binaries-in-source-build.patch

Stop building 7 arcade binaries for .NET Fx.

Do not build .NET Fx binaries in source build.

---

.vsts.pipelines/jobs/ci-linux.yml
build-source-tarball.sh
repos/known-good.proj
repos/package-source-build.proj
src/package-source-build/pack.sh
src/package-source-build/package.proj

Package up source-built artifacts and publish them with CI so they can be used for subsequent builds.

Add source built artifacts tarball

---

patches/msbuild/0001-Do-not-build-for-.NET-Fx-in-source-build.patch
patches/msbuild/0002-Add-Microsoft.Build.Localization-to-msbuild-for-sour.patch
patches/msbuild/0003-Source-build-should-use-prebuilt-System.CodeDom-and-.patch
repos/msbuild.proj

Source-build should not use prebuilt System.CodeDom and System.Resources.Extensions packages

---

.vsts.pipelines/jobs/ci-linux.yml
build-source-tarball.sh
repos/dir.props

This should not be used normally, as it will break the repo and delete local work for the sake of minimizing space.

Add an option to aggressively delete things the tarball doesn't need and turn it on for CI.

---

Documentation/SourceBuildPrebuiltRepoStatus.md

Update patch list

---

patches/arcade/0012-Remove-reference-to-Microsoft-CodeAnalysis-in-Packag.patch

Remove reference to Microsoft.CodeAnalysis,2.8.2 in arcade Packaging project

---

Documentation/Core-FX-Tests.md

CoreFX tests Documentation

---

patches/corefx/0004-Conditionally-include-runtime.native.System.Data.Sql.patch

Conditionally include runtime SystemDataSql packages

---

Documentation/Coherency.md

Add proposed coherency plan.

---

.vsts.pipelines/steps/setup-macos-native.yml

- CMake is now installed on OSX images, just update it

More OSX fixes

---

patches/nuget-client/0007-Do-not-set-RID-in-source-build.patch

Fixes the issue: https://github.com/dotnet/source-build/issues/1283

Remove nuget-client repo indirect prebuilts

---

patches/msbuild/0002-Remove-runtime-identifiers.patch

Port patch to remove msbuild prebuilts

---

.vsts.pipelines/steps/setup-macos-native.yml

This changes our OSX setup to match CoreFX's, which seems to work.

Match OSX setup with CoreFX

---

patches/roslyn/0001-Conditionally-remove-net472-from-TargetFrameworks.patch
patches/roslyn/0002-Don-t-install-2.1.503-for-testing.patch
patches/roslyn/0003-.NET-Core-only-for-VBCSCompiler.patch
patches/roslyn/0004-Do-not-build-NET-Fx-binaries-in-source-build.patch
patches/roslyn/0005-Import-PackageVersions-props-if-exists.patch
patches/roslyn/0006-Get-rid-of-analyzers.patch

Roslyn prebuilts

---

build-source-tarball.sh
support/tarball/tool-bootstrapping/bootstrap.sh

Add a script for bootstrapping the toolset in a distro.

Add tool bootstrapping script

---

.vsts.pipelines/builds/matrix.yml

Update CI legs

---

.vsts.pipelines/jobs/ci-linux.yml

Collect CoreFX testResults

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-linux_bootstrap.yml
.vsts.pipelines/steps/run-bootstrap.yml
x.sh

Add bootstrap leg

---

repos/coreclr-portable.proj
repos/coreclr.proj

Copy coreclr-tools from the portable coreclr build

---

.vsts.pipelines/steps/setup-macos-native.yml
patches/coreclr/0001-glibc-sysctl-deprecation-handling.patch
patches/coreclr/0002-clang9-resolution-to-conditionally-include-allocator.patch

fix OSX CI failures due to clang

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/ci-linux.yml
build.ps1
init-tools.cmd
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/CheckForPoison.cs

[2.1] Update CI images

---

.vsts.pipelines/steps/run-bootstrap.yml

Fixes https://github.com/dotnet/source-build/issues/1584

Fix final-stage tarball artifacts step in CI: missed bin => artifacts change

---

Documentation/planning/arcade-powered-source-build/implementation-plan.md

Updating with the current owner of vstest.

Updating owner for vstest

---

smoke-test.sh

Fixes https://github.com/dotnet/source-build/issues/1580.

Add self-contained and framework-dependent publish tests.

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md

Issue template for the release checklist.

[Doc-only PR] Add release checklist template

---

Documentation/README.md
Documentation/packaging-installation.md

This was asked by some users on gitter. Lets document it!

[release/3.1] Add documentation for packaging source-build

---

.vsts.pipelines/jobs/ci-linux.yml
ProdConFeed.txt
dependencies.props
patches/cli/0001-Persist-ASP.NET-runtime-patch-targeting-default.patch
patches/cli/0003-Remove-System.Security.Principal.Windows-nupkg-ref.patch
repos/cli.proj
repos/core-setup.proj
repos/coreclr.proj
repos/corefx.proj
tools-local/prebuilt-baseline-offline.xml
tools-local/prebuilt-baseline-online.xml

https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.20/2.1.20.md

[release/2.1] Update to July 2020 2.1.516 release (2.1.20)

---

smoke-test.sh

Before this change, running smoke tests on arm64 using:
./build.sh
./build.sh --run-smoke-test
fails with an error that looks like this:
.dotnet/sdk/5.0.100-preview.4.20258.7/MSBuild.dll /bl:source-build-test.binlog /clp:v=m /flp:v=diag /t:RunSmokeTest build.proj
ls: cannot access 'artifacts/x64/Release/dotnet-sdk-5.0*': No such file or directory
This is effectively a port of https://github.com/dotnet/source-build/pull/1652 to the 'master' branch.

Fix smoke tests to run on arm64

---

Documentation/planning/arcade-powered-source-build/README.md
Documentation/planning/arcade-powered-source-build/incremental-official.md

This would have been nice, but isn't actually feasible, and we don't think it's necessary after all.
(The rich diff does a better job of handling the column wrapping than raw diff.)

Arcade-powered source-build: remove the plan to end-to-end test every added intermediate nupkg

---

eng/Version.Details.xml
eng/Versions.props
tools-local/init-build.proj

Update SBRP to version with updated TargetingPacks

---

.vsts.pipelines/jobs/ci-linux_bootstrap.yml

Cherry picks https://github.com/dotnet/source-build/pull/1705

[master] Update 'release/3.1' => 'pre-arcade' SBRP branch in bootstrap CI

---

.gitignore
Directory.Build.props
Directory.Build.targets
build-source-tarball.sh
build.proj
build.sh
repos/Directory.Build.props
repos/Directory.Build.targets
repos/aspnetcore.proj
repos/installer.proj
repos/linker.proj
repos/msbuild.proj
repos/runtime.common.targets
repos/sdk.proj
support/tarball/build.sh
tools-local/init-build.proj

Port https://github.com/dotnet/source-build/pull/1700 to master branch.

[master] Add incremental build

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/prepare-artifacts.yml

Porting #1679 from release/3.1

[master] Add prepare artifacts job

---

patches/runtime/0019-Add-an-option-to-keep-native-debug-symbols.patch
repos/runtime.common.props

This is a backport of https://github.com/dotnet/runtime/pull/39203

Re-enable building with debug symbols again

---

.vsts.pipelines/stages/prepare-artifacts.yml

Port https://github.com/dotnet/source-build/pull/1806 to `master`

[master] Fix prepare-artifacts portable dependency

---

patches/nuget-client/0006-don-t-use-PublicApiAnalyzers.patch

should eliminate Microsoft.CodeAnalysis.PublicApiAnalyzers
@crummel ptal
cc @omajid

nuget.client: don't use PublicApiAnalyzers

---

patches/runtime/0020-System.Private.CoreLib-disable-analyzers.patch

should eliminate StyleCop.Analyzers, StyleCop.Analyzers.Unstable
@crummel ptal
cc @omajid

runtime: System.Private.CoreLib: disable analyzers

---

.vsts.pipelines/jobs/ci-linux.yml

Quick attempt at https://github.com/dotnet/source-build/issues/1823. We'll see if it works in the PR build.

Save prebuilt reports to specific root artifact

---

patches/linker/0002-Remove-apphost-prebuilt-usage.patch

For https://github.com/dotnet/source-build/issues/1905.
Running a local build now to make sure I can see if it's working, not sure yet.

linker: Remove apphost prebuilt usage

---

eng/Version.Details.xml
eng/Versions.props

Internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=897408&view=results

Update SBRP to 1.0.0-beta.20573.3

---

patches/aspnetcore/0018-Make-Microsoft.Win32.SystemEvents-explicit-ref.patch

For https://github.com/dotnet/source-build/issues/1889.

aspnetcore: Make Microsoft.Win32.SystemEvents an explicit ref

---

eng/Version.Details.xml
eng/Versions.props

Fixes https://github.com/dotnet/source-build/issues/1940

Update SBRP to 1.0.0-beta.20607.1

---

eng/SourceBuild.Tarball.targets
repos/arcade.proj

Stop filtering arcade prebuilts for prebuilt check

---

eng/Versions.props

For https://github.com/dotnet/source-build/issues/1892

Use 5.0.0 previously-source-built tar.gz

---

Documentation/planning/arcade-powered-source-build/img/implementation-plan-graph.dot
Documentation/planning/arcade-powered-source-build/img/implementation-plan-graph.svg
Documentation/planning/arcade-powered-source-build/implementation-plan.md

Update table + diagram.
https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&package=Microsoft.SourceBuild.Intermediate.sourcelink&protocolType=NuGet&version=1.1.0-beta-21069-02

Arcade-powered: sourcelink CI implemented

---

smoke-test.sh

.NET Core 2.1, 3.1 and 5.0 use separate strings of text to indicate that the application is running. All include this text, though:
Application started. Press Ctrl+C to shut down.
Update the timeout detection logic to be more flexible and catch this line of text anywhere in the output, not just in the last line.
This brings the timeout for some of these test runs down from 30 seconds to 2 or 3 seconds.
This is a port of #1963 to master.

[release/5.0] Fix smoke test timeout detection to work again

---

Documentation/planning/arcade-powered-source-build/onboarding/README.md
Documentation/planning/arcade-powered-source-build/onboarding/local-onboarding.md

/cc @omajid @crummel @dseefeld

[master] Update ArPow onboarding docs: include patches, onboarding stage ownership

---

Documentation/planning/arcade-powered-source-build/implementation-plan.md

Related: https://github.com/dotnet/source-build/issues/2043. Updating table to match current ownership.

[master] ArPow update: mono/linker champ

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-linux_bootstrap.yml
.vsts.pipelines/jobs/ci-local.yml
.vsts.pipelines/steps/cleanup-unneeded-files.yml
Directory.Build.props
build-source-tarball.sh
eng/Versions.props
repos/Directory.Build.targets
repos/coreclr-portable.proj
repos/coreclr.proj
smoke-test.sh
tools-local/prebuilt-baseline-online.xml

Internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1048145&view=logs&j=64432c0a-6861-509c-a52f-6e964b187d85&t=50c53b57-c1c8-59bd-2da7-2a1bb73968a5.
This should not show up as an external PR build.

Add ARM64 RHEL to CI matrix

---

NuGet.config
build.sh
eng/Version.Details.xml
eng/Versions.props
global.json
patches/aspnetcore/0006-Fix-version-number.patch
patches/aspnetcore/0007-Remove-Yarn-dependency-not-used-in-source-build.patch
patches/aspnetcore/0011-Support-global.json-on-arm64-as-well.patch
smoke-testNuGet.Config
tools-local/prebuilt-baseline-online.xml

- Update repo hashs, version numbers, URLs.
- Update ASP.NET patches.
- Update online prebuilt baseline.
- Update bootstrap SDK version.

Update to 3.1.117 July release.

---

eng/Versions.props

Fixes https://github.com/dotnet/source-build/issues/2380.

Update Versions.props for the 5.0.9/5.0.206 release.

---

NuGet.config

The local view confuses the nuget security analysis task.

[release/3.1] Remove view from feed

---

.vsts.pipelines/builds/matrix.yml
.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-linux_bootstrap.yml
.vsts.pipelines/jobs/ci-local.yml
.vsts.pipelines/steps/cleanup-unneeded-files.yml
build-source-tarball.sh

Internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1180681&view=results.  This won't be visible in the PR because the RHEL builds are internal-only.

[release/5.0] Add x64 RHEL7 and 8 builds.

---

.vsts.pipelines/jobs/ci-local.yml
Documentation/rhel-machine-setup-and-ci.md

I believe this also
Fixes: https://github.com/dotnet/source-build/issues/2628.

RHEL CI and doc improvements

---

.vsts.pipelines/builds/ci.yml

Moves the builds off of the "retail" public AzDO build pools.

[main] Update AzDO pipeline pools

---

.vsts.pipelines/builds/ci.yml

Moves the builds off of the "retail" public AzDO build pools.

[release/6.0] Update AzDO pipeline pools

---

.vsts.pipelines/jobs/ci-local.yml
Documentation/rhel-machine-setup-and-ci.md

* Try out removing temp file and add link to CI machine IP addresses.
* Also remove the submodule dirs.
* Address review comments.

RHEL CI and doc improvements (Port 2627 to release/3.1)

---

.vsts.pipelines/jobs/ci-linux.yml
.vsts.pipelines/jobs/ci-linux_bootstrap.yml
.vsts.pipelines/jobs/ci-local.yml
.vsts.pipelines/steps/run-bootstrap.yml
repos/Directory.Build.targets
tools-local/prebuilt-baseline-online.xml
tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UsageReport/ValidateUsageAgainstBaseline.cs

Attempting to address the following:
- https://github.com/dotnet/source-build/issues/2636
- https://github.com/dotnet/source-build/issues/2729
These are only testable in CI, so I'm letting these run as a draft.

[release/3.1] CI improvements

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md

Updates to a few steps and some formatting cleanup.

Update 6.0 servicing checklist

---

NuGet.config
build.sh
eng/Version.Details.xml
eng/Versions.props
global.json
patches/aspnetcore/0001-Use-non-portable-NETCoreAppRuntime-for-crossgen.patch
patches/aspnetcore/0002-Conditionally-set-PackAsToolShimRID.patch
patches/aspnetcore/0003-Exclude-some-projects-from-source-build.patch
patches/aspnetcore/0004-Remove-Yarn-dependency-not-used-in-source-build.patch
patches/aspnetcore/0005-Revert-to-reference-versions-of-source-built-package.patch
patches/aspnetcore/0006-Add-FreeBSD.patch
patches/aspnetcore/0007-Support-global.json-on-arm64-as-well.patch
patches/aspnetcore/0008-use-sourcebuildRID-to-find-clrjit.patch
patches/aspnetcore/0009-Use-source-built-version-of-MSBuild.patch
patches/aspnetcore/0010-Fix-a-couple-issues.patch
patches/aspnetcore/0011-Don-t-warn-on-CA1416.patch
patches/aspnetcore/0012-Use-source-built-NuGet-for-repo-tasks.patch
patches/aspnetcore/0013-Make-Microsoft.Win32.SystemEvents-explicit-ref.patch
patches/aspnetcore/0014-Don-t-canonicalize-all-ref-packages-to-RTM-versions-.patch
patches/aspnetcore/0015-Don-t-use-RTMVersion-in-source-build.patch
patches/aspnetcore/0016-Emit-RepoTasks.binlog.patch
patches/aspnetcore/0017-Publish-compressed-files-to-a-provided-location.patch
patches/aspnetcore/0018-Disable-nullable-warnings.patch
patches/aspnetcore/0019-Try-to-get-templates-to-build.patch

See https://github.com/dotnet/announcements/issues/210

Update to .NET 5.0.15 / 5.0.212 March 2022 servicing release

---

eng/source-build-release-announcement.md
eng/source-build-release-pr.md
eng/source-build-release.yml
eng/submit-source-build-release-pr.sh

Fixes https://github.com/dotnet/source-build/issues/2632
Submits a PR to dotnet/installer from the dotnet-sb-bot's fork that updates the global.json dotnet version and previously source built artifacts version.

[main] Add pipeline stage to submit source-build updates PR

---

NuGet.config
build.sh
eng/Version.Details.xml
eng/Versions.props
global.json
patches/aspnetcore/0007-Support-global.json-on-arm64-as-well.patch
tools-local/prebuilt-baseline-online.xml

Update to .NET SDK version 5.0.213.

.NET Source-Build 5.0.213 April 2022 Updates

---

Documentation/leak-detection.md
Documentation/poison-report-format.md

Fixes https://github.com/dotnet/source-build/issues/2568.

Add poisoning documentation.

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md

Related to https://github.com/dotnet/source-build/issues/2848

Update release checklist to capture smoke-test prereqs for each release

---

build.sh
eng/Version.Details.xml
eng/Versions.props
patches/aspnetcore/0007-Support-global.json-on-arm64-as-well.patch
tools-local/prebuilt-baseline-online.xml

Updates for .NET source-build May 2022 servicing.

.NET 5.0.17 / 5.0.214 May 2022 Updates

---

README.md

Fixes https://github.com/dotnet/source-build/issues/2602.
In draft mode until https://github.com/dotnet/installer/pull/14038 is approved/merged.

Move source-build instructions to dotnet/installer

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
patches/application-insights/0001-Eliminate-prebuilts.patch
repos/application-insights.proj

This should fix https://github.com/dotnet/source-build/issues/2994.
Also see
* https://github.com/dotnet/sdk/pull/22974

[release/6.0] Update application-insights to 2.19.0

---

README.md

Self-explanatory. One half of https://github.com/dotnet/source-build/issues/3059

[main] Update README to reference 7.0 and remove 5.0 references

---

README.md

Determining information on Homebrew and will update it later.

Add Linux distro information to the readme

---

eng/templates/steps/get-build-info.yml

A little quality-of-life addition that makes troubleshooting and sanity checks easier.

Add links to pipeline runs in release pipelines

---

eng/source-build-release.yml
eng/templates/steps/upload-to-blob-storage.yml

This is needed to facilitate https://github.com/dotnet/source-build/issues/3156
We upload only the CentOS 7 Offline SDK for 6.0, and CentOS 8 Stream Offline for 7.0.

Automatically upload SDK with release pipeline

---

Documentation/sourcebuild-in-repos/new-repo.md

Resolves https://github.com/dotnet/arcade/issues/11817

Update new-repo instructions with VMR steps

---

eng/source-build-release.yml

Fixes https://github.com/dotnet/source-build/issues/3213

Fix quoting error in source-build release pipeline

---

test/NuGet.config

Adds a blank NuGet.config which resolves a problem that was flagged during today's release pipeline run

Resolve a Secure Supply Chain issue

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
eng/templates/stages/release.yml

File cannot contain special chars such as `/` so we will use the gist title instead

Use gist's title as the announcement title

---

eng/templates/stages/release.yml

https://github.com/dotnet/source-build/issues/3317

Use the release tag in the release attachment tarball name

---

eng/templates/steps/initialize-release-info.yml

https://github.com/dotnet/source-build/issues/3317

Use runtime version as the default release tag

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md
eng/gather-prereqs.sh

This script is linked in our release documentation and we want to make the license unambiguous.

[main] Add gather-prereqs script

---

README.md

Fixes: https://github.com/dotnet/source-build/issues/3039

Elaborate on the updated goals for source-build

---

eng/templates/stages/release.yml

Fix `RELEASE_CHANNEL` not being replaced

---

eng/source-build-release-official.yml
eng/templates/stages/mirror.yml

Fixes https://github.com/dotnet/source-build/issues/3384

Allow package mirroring to be skipped

---

eng/templates/stages/mirror.yml

Fixes https://github.com/dotnet/source-build/issues/3375

Fix extra leading `v` in release tag name

---

eng/source-build-release-announcement.md

Make release JSON metadata not installer-specific

---

eng/templates/stages/release.yml

https://github.com/dotnet/source-build/issues/3265

Remove custom tarball attachment from VMR releases

---

eng/templates/steps/initialize-release-info.yml

https://github.com/dotnet/source-build/issues/3376

Use SDK version as the release tag for .NET 6.0/7.0

---

eng/templates/stages/pre-release.yml
eng/templates/steps/initialize-release-info.yml

I think this got somehow broken between all those 5 PRs the other day. More proof we need a PR validation..

Fix the release pipeline initialization step

---

eng/push-tarball.sh

bug fix, variable name change

---

eng/templates/stages/release.yml

Resolves https://github.com/dotnet/source-build/issues/3415

Do not fail dry runs when release tag does not exist yet

---

eng/templates/stages/release.yml

Resolves https://github.com/dotnet/source-build/issues/3449

Do not fail when GitHub release exists already

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md

Fixes dotnet/source-build#3408

Add release checklist step to verify SDK diff tests

---

.github/ISSUE_TEMPLATE/releases/release_checklist.md

Related to https://github.com/dotnet/installer/pull/17074#discussion_r1276540026

Add OmniSharp version update to SB release checklist

---

Documentation/patching-guidelines.md

Related to https://github.com/dotnet/source-build/issues/2237.

Add patch guideline documentation

---

eng/templates/stages/release.yml

This reverts https://github.com/dotnet/source-build/pull/3638 and https://github.com/dotnet/source-build/pull/3644

Revert release stage changes to push commit

---

Documentation/sourcebuild-in-repos/new-repo.md

This document had several out of date references.  It will need a more extensive re-write as the UB project progresses.  I wanted to get these updates completed as we have had a few folks reference this document lately.

Update repo onboarding instructions

---

.github/workflows/check-markdown-links.yml

Closes https://github.com/dotnet/source-build/issues/4833
Validation check: https://github.com/dotnet/source-build/actions/runs/13592675477/job/38002327266?pr=4925

[Check markdown links] Use ubuntu 22.04
